### ISSUE TITLE
Copied __class_getitem__  in declarative Base class forgets attributes

### ISSUE THREAD

**Issue by kasium** [sqlalchemy/sqlalchemy#7462]
### Describe the bug

I guess this is caused by https://github.com/sqlalchemy/sqlalchemy/pull/7381. When using it, all other attributes, e.g. `__table__` are forgotten by the table.

### To Reproduce

```python
T = TypeVar("T", bound="CommonBase")  # noqa

class CommonBase(Generic[T]):
	@classmethod
	def boring(cls: Type[T]) -> Type[T]:
		return cls

@as_declarative()
class Base(CommonBase[T]):
	pass

class Tab(Base["Tab"]):
       __tablename__ = "foo"
	a = Column(Integer, primary_key=True)

assert Tab.__table__
```

### Error

AttributeError: type object 'CommonBase' has no attribute '__table__'

### Versions

OS: Linux
Python: 3.7.1
SQLAlchemy: 1.4.28

**Comment by kasium** [comment]
As always I'm happy to open a PR if you guide me to the right point. Currently, I think, we need to merge the `__class_getitem__ ` of Base and CommonBase

**Comment by zzzeek** [comment]
sure.   In trying to understand what's happening here, IIUC there's no regression here, because previously you couldn't use `Base[typ]` in any case.   Below illustrates if you use `Base` non generically, which was your only option previously, nothing is wrong:

```py
from typing import Generic
from typing import Type
from typing import TypeVar

from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy.orm import as_declarative


T = TypeVar("T", bound="CommonBase")  # noqa

class CommonBase(Generic[T]):
    @classmethod
    def boring(cls: Type[T]) -> Type[T]:
        return cls

@as_declarative()
class Base(CommonBase[T]):
    pass

class Tab1(Base):
    __tablename__ = "foo"
    a = Column(Integer, primary_key=True)

class Tab2(Base["Tab"]):
    __tablename__ = "bar"
    a = Column(Integer, primary_key=True)

assert Tab1.__table__ is not None  # fine
assert Tab2.__table__ is not None  # AttributeError 
```

can you confirm we didn't break anything for anyone here?

**Comment by kasium** [comment]
@zzzeek yes, the example works as you said. W/o generics everything is fine, so no regression

**Comment by zzzeek** [comment]
cool.  I would welcome a PR w/ a new test + a changelog file.

**Comment by kasium** [comment]
Do you have any clue where to start with the analysis?

**Comment by zzzeek** [comment]
I would place a breakpoint() statement into the `__class_getitem__()` method and see what the interpreter is passing there as well as what it's expecting to see as a result, in order to produce the desired behavior.

**Comment by kasium** [comment]
I'll try to share my current investigation
`type(Tab(Base["Tab"]))` --> `<class 'type'>`
`type(Tab(Base))` --> `<class 'sqlalchemy.orm.decl_api.DeclarativeMeta'>`

**Comment by kasium** [comment]
@zzzeek please find some analysis above. I really have the feeling that I need help with the analysis

**Comment by zzzeek** [comment]
one of us would have to find some time to take a look at this.  this is new functionality

**Comment by CaselIT** [comment]
> My current feeling, is, that metaclasses get somehow lost when using generic superclasses. Also class attributes like `registry` are lost. However, a manually added class/instance method/attributes are accessible

this looks like the main candidate for the issue.

I woulder what would happen if instead of coping the `__class_getitem__` here

https://github.com/sqlalchemy/sqlalchemy/blob/3543fcc9c9601e81560d055ceadaea05c75815c0/lib/sqlalchemy/orm/decl_api.py#L790-L791

we would add one that we define, like 
```py
    def __class_getitem__(cls, key):
        return cls
```

**Comment by kasium** [comment]
@CaselIT wow, that works:

```py
from typing import Generic
from typing import Type
from typing import TypeVar

from sqlalchemy import Column
from sqlalchemy import Integer
from sqlalchemy.orm import as_declarative, DeclarativeMeta
from sqlalchemy.testing import fixtures


class DeclarativeBaseTest(fixtures.TestBase):
    def test_class_getitem(self):
        T = TypeVar("T", bound="CommonBase")  # noqa

        class CommonBase(Generic[T]):
            @classmethod
            def boring(cls: Type[T]) -> Type[T]:
                return cls

        @as_declarative()
        class Base(CommonBase[T]):
            foo = 1



        class Tab(Base["Tab"]):
            __tablename__ = "foo"
            a = Column(Integer, primary_key=True)


        assert Tab.foo
        assert Tab.__table__ is not None
        assert Tab.boring()
```

Changed code

```py
        if hasattr(cls, "__class_getitem__"):
            class_dict["__class_getitem__"] = lambda cls, key: cls
```

I wonder why this works and if there are any side effects

**Comment by CaselIT** [comment]
I'm guessing that the `Generic` `__class_getitem__` does something we don't want and is messing the  function in this case.

if you can open a PR it would be great!

**Comment by kasium** [comment]
Sure, I'll do so 😄

**Comment by sqla-tester** [comment]
**Kai Mueller** has proposed a fix for this issue in the **main** branch:

**Fix missing class attributes when using __class_getitem__** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3417

**Comment by sqla-tester** [comment]
**Kai Mueller** has proposed a fix for this issue in the **rel_1_4** branch:

**Fix missing class attributes when using __class_getitem__** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3428
