### ISSUE TITLE
AttributeError: 'list' object has no attribute '_reset_empty'

### ISSUE THREAD

**Issue by ThiefMaster** [sqlalchemy/sqlalchemy#6420]
**Describe the bug**
Using `noload('*')` and then `contains_eager` for another relationship breaks if that relationship has a backref with `lazy='dynamic'`.

**Expected behavior**
No error, this worked fine in 1.3

**To Reproduce**

```py
from sqlalchemy import *
from sqlalchemy.orm import *


Base = declarative_base()


class Foo(Base):
    __tablename__ = 'foo'
    id = Column(Integer, primary_key=True)
    bar_id = Column(Integer, ForeignKey('bar.id'), nullable=False)
    bar = relationship('Bar', backref=backref('bars', lazy='dynamic'))

    def __repr__(self):
        return f'<Foo {self.id}>'


class Bar(Base):
    __tablename__ = 'bar'
    id = Column(Integer, primary_key=True)

    def __repr__(self):
        return f'<Bar {self.id}>'


e = create_engine('postgresql:///test', echo=True)
Base.metadata.create_all(e)
s = Session(e)


if not s.query(Foo).count():
    s.add(Foo(bar=Bar()))
    s.commit()


print(s.query(Foo).join(Foo.bar).options(noload('*'), contains_eager(Foo.bar)).all())
```

**Error**

```pytb
Traceback (most recent call last):
  File "/tmp/satest.py", line 35, in <module>
    print(s.query(Foo).join(Foo.bar).options(noload('*'), contains_eager(Foo.bar)).all())
  File "/home/adrian/dev/indico/py3/env/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2683, in all
    return self._iter().all()
  File "/home/adrian/dev/indico/py3/env/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1335, in all
    return self._allrows()
  File "/home/adrian/dev/indico/py3/env/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 408, in _allrows
    rows = self._fetchall_impl()
  File "/home/adrian/dev/indico/py3/env/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1243, in _fetchall_impl
    return self._real_result._fetchall_impl()
  File "/home/adrian/dev/indico/py3/env/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1636, in _fetchall_impl
    return list(self.iterator)
  File "/home/adrian/dev/indico/py3/env/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 124, in chunks
    rows = [proc(row) for row in fetch]
  File "/home/adrian/dev/indico/py3/env/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 124, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/home/adrian/dev/indico/py3/env/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 933, in _instance
    _populate_full(
  File "/home/adrian/dev/indico/py3/env/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 1104, in _populate_full
    populator(state, dict_, row)
  File "/home/adrian/dev/indico/py3/env/lib/python3.9/site-packages/sqlalchemy/orm/strategies.py", line 2566, in load_scalar_from_joined_new_row
    dict_[key] = _instance(row)
  File "/home/adrian/dev/indico/py3/env/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 933, in _instance
    _populate_full(
  File "/home/adrian/dev/indico/py3/env/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 1104, in _populate_full
    populator(state, dict_, row)
  File "/home/adrian/dev/indico/py3/env/lib/python3.9/site-packages/sqlalchemy/orm/strategies.py", line 600, in invoke_no_load
    attributes.init_state_collection(state, dict_, self.key)
  File "/home/adrian/dev/indico/py3/env/lib/python3.9/site-packages/sqlalchemy/orm/attributes.py", line 2130, in init_state_collection
    adapter._reset_empty()
AttributeError: 'list' object has no attribute '_reset_empty'
```

**Versions.**
 - OS: Linux
 - Python: 3.9.4
 - SQLAlchemy: 1.4.9
 - Database: Postgres
 - DBAPI: psycopg2

**Comment by zzzeek** [comment]
thanks for reporting

https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2801

**Comment by ThiefMaster** [comment]
Thanks for the quick fix :) Any ETA for the next bugfix release?

**Comment by CaselIT** [comment]
Not really a firm eta, but I would think this week since there are already 3-4 regression bug merged other than this one https://github.com/sqlalchemy/sqlalchemy/tree/master/doc/build/changelog/unreleased_14

you can in the meantime install from git using `pip install git+https://github.com/sqlalchemy/sqlalchemy` (or a similar syntax)
