### ISSUE TITLE
SQLAlchemy 1.4 Python 3.9.5 KeyError: 'Mapped'

### ISSUE THREAD

**Issue by farbiondriven** [sqlalchemy/sqlalchemy#6929]
### SQLAlchemy 1.4 Python 3.9.5 KeyError: 'Mapped'

running mypy fails, after upgrading to python 3.9.5. Worked perfectly with python 3.8.

app/db/engine.py:13: error: INTERNAL ERROR -- Please try using mypy master on Github:
https://mypy.readthedocs.io/en/stable/common_issues.html#using-a-development-mypy-build
Please report a bug at https://github.com/python/mypy/issues
version: 0.910
Traceback (most recent call last):
  ...
  File "/home/fabio/remark/DeviceManagement/.venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/plugin.py", line 128, in _dynamic_class_hook
    _add_globals(ctx)
  File "/home/fabio/remark/DeviceManagement/.venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/plugin.py", line 273, in _add_globals
    util.add_global(ctx, "sqlalchemy.orm.attributes", "Mapped", "__sa_Mapped")
  File "/home/fabio/remark/DeviceManagement/.venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/util.py", line 168, in add_global
    lookup_sym: SymbolTableNode = ctx.api.modules[module].names[
**KeyError: 'Mapped'**
app/db/engine.py:13: : note: use --pdb to drop into pdb

### To Reproduce

```python
from sqlalchemy import create_engine, MetaData
from sqlalchemy.orm.decl_api import declarative_base
Base = declarative_base(metadata=MetaData())

class Analytic(Base):
    """Analytics [Types of video analytics to be performed]

    Arguments:
        db {[type]} -- [description]
    """

    __tablename__ = "analytic"

    analytic_id: int = Column(Integer, primary_key=True)
    name: str = Column(String(300), nullable=False)
```

### Error

```
mypy app --show-traceback
  File "/home/fabio/remark/DeviceManagement/.venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/plugin.py", line 273, in _add_globals
    util.add_global(ctx, "sqlalchemy.orm.attributes", "Mapped", "__sa_Mapped")
  File "/home/fabio/remark/DeviceManagement/.venv/lib/python3.9/site-packages/sqlalchemy/ext/mypy/util.py", line 168, in add_global
    lookup_sym: SymbolTableNode = ctx.api.modules[module].names[
KeyError: 'Mapped'

```
with Base class defined as such:
```

from sqlalchemy import  MetaData
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base(metadata=MetaData())
```

mypy gives errors such as:
```
app/model/venue.py:36: error: Incompatible types in assignment (expression has type "Column[str]", variable has type "str")
app/model/settings.py:24: error: Incompatible types in assignment (expression has type "Column[int]", variable has type "int")
app/model/floor.py:15: error: Module "sqlalchemy.orm" has no attribute "Mapped"; maybe "Mapper"?
app/model/floor.py:50: error: Incompatible types in assignment (expression has type "RelationshipProperty[<nothing>]", variable has type "List[Location]")
```

### Versions

- OS: Ubuntu 20.04
- Python: 3.9.5
- SQLAlchemy: 1.4.23
- Database: MySQL
- DBAPI: Pymysql

**Comment by zzzeek** [comment]
mypy finds no issues here, I think you probably need to install [sqlalchemy2-stubs](github.com/sqlalchemy/sqlalchemy2-stubs)

**Comment by zzzeek** [comment]
hmmm python 3.9.5, let me check

**Comment by zzzeek** [comment]
nope im on 3.9.6 here.   make sure you install those stubs

**Comment by farbiondriven** [comment]
Managed to fix it by:

1. removing `mapper_registry = registry()`
2. replacing `from sqlalchemy.ext.declarative import DeclarativeMeta`
with `from sqlalchemy.orm.decl_api import DeclarativeMeta`

3. manually downloading the stubs so, replacing
`SQLAlchemy[mypy]==1.4.23`
with 
```
sqlalchemy==1.4.23
sqlalchemy2-stubs==0.0.2a10
```

Not sure what actually fixed it, but thanks a lot for the quick reply anyway !

**Comment by zzzeek** [comment]
DeclarativeMeta should be able to come from "sqlalchemy.orm".

not sure about the install part of it

cant reproduce here in any case, congrats fixing.
