### ISSUE TITLE
support Mapped[str | None] on Python 3.9 (somehow?)

### ISSUE THREAD

**Issue by JJMC89** [sqlalchemy/sqlalchemy#9110]
### Describe the bug

Annotating an attribute as optional with `Mapped[str | None]` with `from __future__ import annotations` in Python < 3.10 raises `sqlalchemy.exc.ArgumentError`.

The same exception occurs with other types, e.g., `Mapped[bool | None]`, `Mapped[int | None]`.

### To Reproduce

```python
from __future__ import annotations

from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

class Base(DeclarativeBase):
    pass

class Foo(Base):
    __tablename__ = "foo"

    id: Mapped[int] = mapped_column(primary_key=True)
    foo:  Mapped[str | None]
```

### Error

```
Traceback (most recent call last):
  File "/tmp/sqlalchemy/venv/lib/python3.9/site-packages/sqlalchemy/util/typing.py", line 174, in eval_expression
    annotation = eval(expression, base_globals, None)
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/sqlalchemy/venv/lib/python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 1376, in _extract_mappable_attributes
    value.declarative_scan(
  File "/tmp/sqlalchemy/venv/lib/python3.9/site-packages/sqlalchemy/orm/properties.py", line 681, in declarative_scan
    self._init_column_for_annotation(
  File "/tmp/sqlalchemy/venv/lib/python3.9/site-packages/sqlalchemy/orm/properties.py", line 717, in _init_column_for_annotation
    argument = de_stringify_annotation(
  File "/tmp/sqlalchemy/venv/lib/python3.9/site-packages/sqlalchemy/util/typing.py", line 147, in de_stringify_annotation
    annotation = eval_expression(annotation, originating_module)
  File "/tmp/sqlalchemy/venv/lib/python3.9/site-packages/sqlalchemy/util/typing.py", line 176, in eval_expression
    raise NameError(
NameError: Could not de-stringify annotation 'str | None'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/sqlalchemy/t.py", line 8, in <module>
    class Foo(Base):
  File "/tmp/sqlalchemy/venv/lib/python3.9/site-packages/sqlalchemy/orm/decl_api.py", line 706, in __init_subclass__
    _as_declarative(cls._sa_registry, cls, cls.__dict__)
  File "/tmp/sqlalchemy/venv/lib/python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 234, in _as_declarative
    return _MapperConfig.setup_mapping(registry, cls, dict_, None, {})
  File "/tmp/sqlalchemy/venv/lib/python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 315, in setup_mapping
    return _ClassScanMapperConfig(
  File "/tmp/sqlalchemy/venv/lib/python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 557, in __init__
    self._extract_mappable_attributes()
  File "/tmp/sqlalchemy/venv/lib/python3.9/site-packages/sqlalchemy/orm/decl_base.py", line 1388, in _extract_mappable_attributes
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not resolve all types within mapped annotation: "Mapped[str | None]".  Ensure all types are written correctly and are imported within the module in use.
``` 

### Versions

- OS: Ubuntu 22.04
- Python: 3.9.16
- SQLAlchemy: 2.0.0rc2
- Database: n/a
- DBAPI (eg: psycopg, cx_oracle, mysqlclient): n/a

### Additional context

Annotating with `Mapped[Optional[str]]` will work as expected.

**Comment by zzzeek** [comment]
do you have interest in working on a PR ?  we dont have any checks for python 3.9, if it has future support, then different APIs internally would need to be used I am assuming, and I dont know what those are.  I dont know how to make it work in 3.9.

**Comment by zzzeek** [comment]
more succinctly - 

can you get this script to run in python 3.9 ?    still trying things locally without luck

```py
from __future__ import annotations

eval("int | None")
```

**Comment by zzzeek** [comment]
not supported: https://peps.python.org/pep-0236/#resolved-problem-runtime-compilation

would need to use exec

**Comment by zzzeek** [comment]
exec doesn't work.  would need to use https://peps.python.org/pep-0264/

**Comment by zzzeek** [comment]
pep264 ...doesnt work  ?   

```py
from __future__ import annotations
import __future__


code = compile("int | None", "<string>", "eval", __future__.annotations.compiler_flag)
eval(code)

```

**Comment by zzzeek** [comment]
OK.  My current understanding is this can't be done.   The usage of "future annotations" is just a hack which keeps the interpretation of the objects as strings, but does not actually implement runtime syntax for things like `int | None`, meaning we can't evaluate these and get the actual symbols represented at runtime, which is something that we require in order to know what runtime type we're dealing with.

**Comment by zzzeek** [comment]
confirmed, Python std lib cannot read these either.  So 3.9 does not in fact support pipe syntax at all and does not implement it within "__future__" except as a side effect.

```py
from __future__ import annotations
import typing

def my_func(x: int | None) -> None:
    pass

print(typing.get_type_hints(my_func))
```

python 3.10:

```
{'x': int | None, 'return': <class 'NoneType'>}

```

python 3.9:

```
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test4.py", line 7, in <module>
    print(typing.get_type_hints(my_func))
  File "/opt/python-3.9.16/lib/python3.9/typing.py", line 1497, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/opt/python-3.9.16/lib/python3.9/typing.py", line 292, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/opt/python-3.9.16/lib/python3.9/typing.py", line 554, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

```
