### ISSUE TITLE
Alternative to _decl_class_registry in 1.4?

### ISSUE THREAD

**Issue by cuchoi** [sqlalchemy/sqlalchemy#6080]
In 1.4 when I call `Base._decl_class_registry.values()` to get the list of classes associated with that Base I get `AttributeError: type object 'Base' has no attribute '_decl_class_registry'`. It worked in 1.3.X and I was wondering if there is an alternative way to get the list of classes in 1.4.

Thanks for all the work in sqlalchemy! Excited for the 1.4/2.0 new model.

**Versions**
 - OS: macOS 10.14.6
 - Python: Python 3.7.9
 - SQLAlchemy: 1.4.0
 - Database: Postgres 11.6
 - DBAPI: psycopg2

**Comment by lindycoder** [comment]
`model.registry._class_registry` was a valid replacement for the way we use it.  

Would be great to have an official way of listing all tables in the registry.   Maybe there is and i can't find it?

**Comment by lindycoder** [comment]
Our personal use case is to use data generation in tests.   We pass in a model and the generation will make sure the foreign keys exists by itself.  This is roughly done by:
```
table_name, col_name = foreign_key.target_fullname.split('.')

for value in model.registry._class_registry.values():
    if getattr(value, '__tablename__', None) == table_name:
        foreign_table = value
```

If there's a better way of obtaining a foreign key's table object, i'm all ears, if not i need to loop the registry

**Comment by CaselIT** [comment]
[`metadata.tables`](https://docs.sqlalchemy.org/en/14/core/metadata.html?highlight=metadata#sqlalchemy.schema.MetaData.tables) contains all the tables so to get the table you can just do `meta.tables[table_name]`.

But from the example it seems that you are using the model class object. Is that what you need?

**Comment by lindycoder** [comment]
Yes i'm sorry for the confusion, i just realized it trying to use metadata tables, i do need class objects

**Comment by CaselIT** [comment]
Then I think the public api would be use [`registry.mappers`](https://docs.sqlalchemy.org/en/14/orm/mapping_api.html?highlight=registry#sqlalchemy.orm.registry.mappers) to get all the mappers, then to get the class object you can use [`Mapper.class_`](https://docs.sqlalchemy.org/en/14/orm/mapping_api.html?highlight=registry#sqlalchemy.orm.Mapper.class_)

@zzzeek other suggestions

**Comment by zzzeek** [comment]
now that we have "registry" we can add a nice API for whatever we want.   I think .mappers is probably good maybe we should also have get_mapper_by_classname().  when you have a mapper, just call .class_ on it, thats your mapped class.

**Comment by zzzeek** [comment]
> Our personal use case is to use data generation in tests. We pass in a model and the generation will make sure the foreign keys exists by itself. This is roughly done by:
> 
> ```
> table_name, col_name = foreign_key.target_fullname.split('.')
> 
> for value in model.registry._class_registry.values():
>     if getattr(value, '__tablename__', None) == table_name:
>         foreign_table = value
> ```
> 
> If there's a better way of obtaining a foreign key's table object, i'm all ears, if not i need to loop the registry

I believe ForeignKeyConstraint() has a [referred_table](https://docs.sqlalchemy.org/en/14/core/constraints.html?highlight=referred_table#sqlalchemy.schema.ForeignKeyConstraint.referred_table) accessor that will give you the Table directly.   ForeignKey will give the Column: https://docs.sqlalchemy.org/en/14/core/constraints.html?highlight=referred_table#sqlalchemy.schema.ForeignKey.column  
from which you can get the Table.

**Comment by lindycoder** [comment]
@zzzeek very sorry for the confusion, I'm trying to get the class not the table.

**Comment by CaselIT** [comment]
Mike does the registry have a table->mapper mapping ?

**Comment by zzzeek** [comment]
no we've never done that.   it's one of those things that are hard to generalize:

1. a table can have any number of mappings on it.  so it's not table->cls, its table->[classes].  that will already annoy people

2. if i get the mappers for a table, does that include mappers that map to a join of that table?  to a select of that table?

3. what do I get if a bunch of single-inheritnace mappers are all mapped in a hierarchy on that table?   similarly for joined inheritance which is the same as question 2

if we provide .mappers, at least people can iterate through it and interpret the collection as they'd want.

**Comment by zzzeek** [comment]
to be clear I think we can do this because we can key everything on _get_cache_key() and make it very easy to use.  you can find a class mapped againast a select() by just making an equivalent select() and asking for that.

**Comment by maquino1985** [comment]
> now that we have "registry" we can add a nice API for whatever we want. I think .mappers is probably good maybe we should also have get_mapper_by_classname(). when you have a mapper, just call .class_ on it, thats your mapped class.

Once the ORM has been initialized and the classes are loaded, the Base._decl_class_registry() provided the full list of every mapped class (or Table) object.  This is important for too many use cases to get into specifics.

Now, at that same point where Base._decl_class_registry() would have all of that information, the Base class has a ._sa_registry with the ORM classes (but missing all the tables etc). Presumably, the registry would be the replacement for the previous decl_class_registry but it has _nothing_ in it.  Why is the registry empty or how do we get back the functionality of the 1.3 decl_class_registry()? I'm trying to upgrade from 1.3 -> 1.4 but this is a complete blocker...

<img width="569" alt="image" src="https://user-images.githubusercontent.com/13229385/215611690-43cf2d7f-5a9f-4e10-9729-5e6974838515.png">
<img width="569" alt="image" src="https://user-images.githubusercontent.com/13229385/215611728-570aa832-8243-4d32-8b76-7c9f432a1427.png">

**Comment by ahegdeTG** [comment]
Hello,
I'm working on SQLAlchemy v1.4.51 and I get the same error ("AttributeError: type object 'Base' has no attribute '_decl_class_registry' ") when I call Base._decl_class_registry.values() as well. Has this issue been resolved in a more recent version of the package or is this still an open issue?

**Comment by zzzeek** [comment]
there's no official feature for this as yet, issue is opened, so for now you will have to alter your private API access to what is mentioned in https://github.com/sqlalchemy/sqlalchemy/issues/6080#issuecomment-801197345
