### ISSUE TITLE
mapped select interpreted as table , stack trace in 2.0

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#8812]
pretty weird we have no tests for this, make this part of eager default tests

```py
from sqlalchemy import Column
from sqlalchemy import create_engine
from sqlalchemy import Integer
from sqlalchemy import select
from sqlalchemy import String
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import Session

Base = declarative_base()


class A(Base):
    __tablename__ = "a"

    id = Column(Integer, primary_key=True)
    data = Column(String, server_default="data")


# stmt = select(A.__table__).union(select(A.__table__)).subquery()

stmt = select(A.__table__).subquery()

class C(Base):
    __table__ = stmt

    __mapper_args__ = {"eager_defaults": True}


e = create_engine("sqlite://", echo=True)
Base.metadata.create_all(e)

s = Session(e)
s.add(C(id=1))
s.flush()

```

```
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/test3.py", line 35, in <module>
    s.flush()
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/session.py", line 3954, in flush
    self._flush(objects)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/session.py", line 4090, in _flush
    with util.safe_reraise():
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/langhelpers.py", line 148, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/session.py", line 4051, in _flush
    flush_context.execute()
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/unitofwork.py", line 467, in execute
    rec.execute(self)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/unitofwork.py", line 644, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/orm/persistence.py", line 996, in _emit_insert_statements
    or not base_mapper.local_table.implicit_returning
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/util/langhelpers.py", line 1128, in __get__
    return self.fget(obj)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/sql/selectable.py", line 1640, in implicit_returning
    return self.element.implicit_returning  # type: ignore
AttributeError: 'Select' object has no attribute 'implicit_returning'
```

**Comment by zzzeek** [comment]
likely introduced by 466ed5b53a3

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**ensure implicit_returning is checked on a Table instance** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4203
