### ISSUE TITLE
Regression in Select.values() in 2.0

### ISSUE THREAD

**Issue by prousso** [sqlalchemy/sqlalchemy#11483]
### Describe the bug

In 2.0 we can't use `values()` and populated values with a dictionary when a column is called metadata.
It worked before in 1.4.X

### SQLAlchemy Version in Use

2.0.30

### DBAPI (i.e. the database driver)

psycopg2

### Database Vendor and Major Version

PG14

### Python Version

3.12.3

### Operating system

Linux

### To Reproduce

```python
import uuid

from sqlalchemy import Column, ARRAY
from sqlalchemy import create_engine
from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import Session


Base = declarative_base()


class Instance(Base):
    __tablename__ = "instance"

    id = Column(postgresql.UUID(as_uuid=True), primary_key=True)
    metadata_ = Column(
        "metadata",
        ARRAY(postgresql.UUID(as_uuid=True)),
        default=list,
        server_default="{}",
        nullable=False,
        doc="The list of metadata.",
    )


e = create_engine("postgresql://aaaa:bbbb@localhost:10100/cccc", echo=True)
Base.metadata.drop_all(e)
Base.metadata.create_all(e)
session = Session(e)
entities = [{"id": uuid.UUID(int=1), "metadata": []}]


pk_names = [pk.name for pk in Instance.__mapper__.primary_key]
query = postgresql.insert(Instance)
query = query.on_conflict_do_update(
    index_elements=pk_names,
    set_={
        column.name: query.excluded[column.name]
        for column in Instance.__table__.columns
        if column.name not in pk_names
    },
)
values = sorted(
    entities, key=lambda entity: tuple(entity[pk_name] for pk_name in pk_names)
)
query = query.values(values)

session.execute(query)
```

### Error

```
Traceback (most recent call last):
  File "/home/aaaaaaa/projects/core/cactus.py", line 48, in <module>
    query = query.values(values)
            ^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in values
  File "/home/aaaaaaa/projects/core/venv/lib/python3.12/site-packages/sqlalchemy/sql/base.py", line 279, in _generative
    x = fn(self, *args, **kw)
        ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in values
  File "/home/aaaaaaa/projects/core/venv/lib/python3.12/site-packages/sqlalchemy/sql/base.py", line 312, in check
    return fn(self, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaaaaaa/projects/core/venv/lib/python3.12/site-packages/sqlalchemy/sql/dml.py", line 1127, in values
    self._multi_values += (multi_kv_generator(self, arg),)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aaaaaaa/projects/core/venv/lib/python3.12/site-packages/sqlalchemy/orm/bulk_persistence.py", line 435, in _get_multi_crud_kv_pairs
    dict(
  File "/home/aaaaaaa/projects/core/venv/lib/python3.12/site-packages/sqlalchemy/orm/bulk_persistence.py", line 397, in _get_orm_crud_kv_pairs
    desc._bulk_update_tuples(v),
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MetaData' object has no attribute '_bulk_update_tuples'
```

**Comment by zzzeek** [comment]
hi -

your code essentially does this:

    stmt = insert(Instance).values({"metadata": value})

your `Instance` entity does not have a mapped attribute named "metadata".  It has an attribute named "metadata_".   So you would either use that:

    stmt = insert(Instance).values({"metadata_": value})

Or more simply, since you are referring to the "instance" table in your values expression, indicate that you want to work against the mapped table, not the entity:

    stmt = insert(Instance.__table__).values({"metadata": value})

Change is documented at https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#orm-enabled-insert-upsert-update-and-delete-statements-with-orm-returning

the change specifically here is listed at https://docs.sqlalchemy.org/en/20/changelog/whatsnew_20.html#id3

**Comment by prousso** [comment]
Sorry but I have a typing issue with this syntax `insert(Instance.__table__)`
```python
error: Argument 1 to "insert" has incompatible type "FromClause"; expected
"TableClause | Join | Alias | CTE | type[Any] | Inspectable[_HasClauseElement[Any]] | _HasClauseElement[Any]"  [arg-type]
```

**Comment by CaselIT** [comment]
any reason for using `insert(Instance.__table__)` instead of `insert(Instance)`?

**Comment by prousso** [comment]
Sorry I found my answer https://github.com/sqlalchemy/sqlalchemy/issues/10907#issuecomment-1902208398
Yes because I do a `.values({"metadata": value})`

**Comment by CaselIT** [comment]
This should work without requiring the use of `__table__`:
`insert(Instance).values({"metadata": value})`

**Comment by zzzeek** [comment]
> Sorry @zzzeek but I have a typing issue with this syntax `insert(Instance.__table__)`
> 
> ```python
> error: Argument 1 to "insert" has incompatible type "FromClause"; expected
> "TableClause | Join | Alias | CTE | type[Any] | Inspectable[_HasClauseElement[Any]] | _HasClauseElement[Any]"  [arg-type]
> ```

this requires a `typing.cast()`.  a mapped class can be mapped to any `FromClause` but `insert()` expects a `Table`, which is a specific subclass of `FromClause`.  Since you know in this case that `Instance.__table__` is definitely a `Table`, you need to tell the typechecker that this is known using `cast()`.

**Comment by kkozmic** [comment]
Why was this closed? This is an issue. I just upgraded to v2.0.36 and I hit what appears to be this exact issue.

```python
Base = declarative_base()


class SomeData(Base): 

    __tablename__ = "some_data"
    __table_args__ = {"schema": "some_schema"}

    id = Column(UUID(as_uuid=True), primary_key=True, server_default=FetchedValue())
    additional_metadata = Column(JSONB, name="metadata", nullable=True)
    # ...a few more properties

    @hybrid_property
    def user_locale(self) -> str | None:
        return (
            self.additional_metadata.get("user_locale")
            if self.additional_metadata
            else None
        )

    @user_locale.inplace.setter
    def _user_locale_setter(self, value: str | None) -> None:
        # Set the 'user_locale' value inside the 'metadata' JSONB column
        if self.additional_metadata is None:
            self.additional_metadata = {}
        self.additional_metadata["user_locale"] = value
```

this is the code that fails in v2, but worked in v1.4
```python
                stmt = insert(SomeData).values(
                    id=u["id"],
                    metadata=u.get("metadata"),
                    # ... the other properties
                )

                session.execute(stmt)

```
Fails with
```
E                       AttributeError: 'MetaData' object has no attribute '_bulk_update_tuples'

.venv/lib/python3.11/site-packages/sqlalchemy/orm/bulk_persistence.py:419: AttributeError
```

I'm happy to provide more context. At this point I'm just curious why it's been closed

**Comment by CaselIT** [comment]
> At this point I'm just curious why it's been closed

It's explained here https://github.com/sqlalchemy/sqlalchemy/issues/11483#issuecomment-2162967948

Use the name of the orm attribute, so additional_metadata on your example
