### ISSUE TITLE
per-state change in association proxy breaks discriminator_on_association.py

### ISSUE THREAD

**Issue by zzzeek** [sqlalchemy/sqlalchemy#4401]
because we are putting .parent on CustomerAddresAssociation, SupplierAddressAssocaition and not AddressAssociation

```
Traceback (most recent call last):
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/ext/associationproxy.py", line 217, in _as_instance
    return class_.__dict__[self.key + "_inst"]
KeyError: '_AssociationProxy_association_140197095777336_inst'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/generic_associations/discriminator_on_association.py", line 144, in <module>
    print(address)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/ext/associationproxy.py", line 173, in __get__
    inst = self._as_instance(class_)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/ext/associationproxy.py", line 221, in _as_instance
    result = AssociationProxyInstance.for_proxy(self, owner)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/ext/associationproxy.py", line 315, in for_proxy
    target_class, value_attr)
  File "/home/classic/dev/sqlalchemy/lib/sqlalchemy/ext/associationproxy.py", line 341, in _cls_unwrap_target_assoc_proxy
    attr = getattr(target_class, value_attr)
AttributeError: type object 'AddressAssociation' has no attribute 'parent'

```

regression due to #3423

**Comment by zzzeek** [comment]
here's the test, polymorphic access to an attribute


```

from sqlalchemy import *
from sqlalchemy.orm import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.associationproxy import association_proxy

Base = declarative_base()


class A(Base):
    __tablename__ = 'a'

    id = Column(Integer, primary_key=True)
    b_id = Column(ForeignKey('b.id'))
    b = relationship("B")

    data = association_proxy("b", "data")


class B(Base):
    __tablename__ = 'b'
    id = Column(Integer, primary_key=True)
    type = Column(String)

    __mapper_args__ = {
        "polymorphic_on": type,
        "polymorphic_identity": "b"
    }


class B1(B):
    data = Column(String)
    __mapper_args__ = {
        "polymorphic_identity": "b1"
    }


a1 = A(b=B1(data='hi'))

print(a1.data)
```
