### ISSUE TITLE
The SQLAlchemy 1.4 C extension fails to compile on Python 3.13

### ISSUE THREAD

**Issue by musicinmybrain** [sqlalchemy/sqlalchemy#11499]
### Describe the bug

The C extension for SQLAlchemy 1.4 uses `_PyArg_NoKeywords()`, an undocumented private API that [was moved to the `pycore_modsupport.h` internal C API in Python 3.13](https://github.com/python/cpython/issues/110964).

As a result, the C extension fails to build on Python 3.13.

```
  lib/sqlalchemy/cextension/resultproxy.c: In function ‘tuplegetter_new’:
  lib/sqlalchemy/cextension/resultproxy.c:831:10: error: implicit declaration of function ‘_PyArg_NoKeywords’ [-Wimplicit-function-declaration]
    831 |     if (!_PyArg_NoKeywords("tuplegetter", kwds))
        |          ^~~~~~~~~~~~~~~~~
```

### SQLAlchemy Version in Use

1.4.52 (or, `rel_1_4` branch, currently at b13cdd19388a4c6d99647acc8632861e69bd25e1)

### DBAPI (i.e. the database driver)

N/A

### Database Vendor and Major Version

N/A

### Python Version

3.13.0b1

### Operating system

Fedora 40

### To Reproduce

```python
$ gh repo clone sqlalchemy/sqlalchemy
$ cd sqlalchemy
$ git checkout rel_1_4
$ python3.13 -m venv _e
(_e) $ pip install build
(_e) $ REQUIRE_SQLALCHEMY_CEXT=1 python -m build
```

### Error

```
gcc -fno-strict-overflow -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -fcf-protection -fexceptions -fcf-protection -fexceptions -fcf-protection -fexceptions -O3 -fPIC -I/tmp/build-env-l1j4cq8g/include -I/usr/include/python3.13 -c lib/sqlalchemy/cextension/resultproxy.c -o build/temp.linux-x86_64-cpython-313/lib/sqlalchemy/cextension/resultproxy.o -Wundef -Werror=implicit-function-declaration
lib/sqlalchemy/cextension/resultproxy.c: In function ‘tuplegetter_new’:
lib/sqlalchemy/cextension/resultproxy.c:831:10: error: implicit declaration of function ‘_PyArg_NoKeywords’ [-Wimplicit-function-declaration]
  831 |     if (!_PyArg_NoKeywords("tuplegetter", kwds))
      |          ^~~~~~~~~~~~~~~~~
***************************************************************************
NOTE: C extension build is required because REQUIRE_SQLALCHEMY_CEXT is set, and the build has failed; will not degrade to non-C extensions
***************************************************************************
Traceback (most recent call last):
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/_distutils/unixccompiler.py", line 188, in _compile
    self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
    spawn(cmd, dry_run=self.dry_run, **kwargs)
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/_distutils/spawn.py", line 68, in spawn
    raise DistutilsExecError(f"command {cmd!r} failed with exit code {exitcode}")
distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 74, in build_extension
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/command/build_ext.py", line 252, in build_extension
    _build_ext.build_extension(self, ext)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
    objects = self.compiler.compile(
        sources,
    ...<5 lines>...
        depends=ext.depends,
    )   
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/_distutils/ccompiler.py", line 600, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/_distutils/unixccompiler.py", line 190, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command '/usr/bin/gcc' failed with exit code 1
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ben/Downloads/sqlalchemy/_e/lib64/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in <module>
    main()
    ~~~~^^
  File "/home/ben/Downloads/sqlalchemy/_e/lib64/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 357, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
                             ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ben/Downloads/sqlalchemy/_e/lib64/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 271, in build_wheel
    return _build_backend().build_wheel(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        wheel_directory, config_settings, metadata_directory
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/build_meta.py", line 410, in build_wheel
    return self._build_with_temp_dir(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        ['bdist_wheel'],
        ^^^^^^^^^^^^^^^^
    ...<3 lines>...
        self._arbitrary_args(config_settings),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
    self.run_setup()
    ~~~~~~~~~~~~~~^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/build_meta.py", line 487, in run_setup
    super().run_setup(setup_script=setup_script)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/build_meta.py", line 311, in run_setup
    exec(code, locals())
    ~~~~^^^^^^^^^^^^^^^^
  File "<string>", line 166, in <module>
  File "<string>", line 146, in run_setup
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
    ~~~~~~~~~~~~~~~~~^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
    ~~~~~~~~~~~~~~~~^^^^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/dist.py", line 968, in run_command
    super().run_command(command)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
    ~~~~~~~~~~~^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/wheel/bdist_wheel.py", line 368, in run
    self.run_command("build")
    ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/dist.py", line 968, in run_command
    super().run_command(command)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
    ~~~~~~~~~~~^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/dist.py", line 968, in run_command
    super().run_command(command)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
    ~~~~~~~~~~~^^
  File "<string>", line 68, in run
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/command/build_ext.py", line 91, in run
    _build_ext.run(self)
    ~~~~~~~~~~~~~~^^^^^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
    self.build_extensions()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
    self._build_extensions_serial()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/tmp/build-env-l1j4cq8g/lib64/python3.13/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
    self.build_extension(ext)
    ~~~~~~~~~~~~~~~~~~~~^^^^^
  File "<string>", line 76, in build_extension
BuildFailed

ERROR Backend subprocess exited when trying to invoke build_wheel
```

**Comment by CaselIT** [comment]
Hi,

Do you have a suggested replacement function that can be used?

**Comment by zzzeek** [comment]
Well we might have to use version specific defines to handle this, there's already a bunch of that in the old C extensions

We probably need to set up a python version EOL for 1.4 at some point

**Comment by musicinmybrain** [comment]
> Hi,
> 
> Thanks for reporting. Do you have a suggested replacement function that can be used?

The best suggestion I have is to just imitate [its implementation](https://github.com/python/cpython/blob/3a83b172af1bde6032ecca7c1a2e6b82d06325e1/Python/getargs.c#L2839-L2861), which is straightforward and uses only functions that are still in the public C API. I plant to submit a PR for that approach.

**Comment by musicinmybrain** [comment]
> We probably need to set up a python version EOL for 1.4 at some point

This is probably true. On the other hand, speaking as a Fedora packager (but not a primary maintainer of any of the SQLAlchemy packages in Fedora) we still have a [`python-sqlalchemy1.4` compat package](https://src.fedoraproject.org/rpms/python-sqlalchemy1.4), and there are some significant packages that haven’t been able to migrate to SQLAlchemy 2.0 yet, so we have good reason to keep 1.4 around at least for Python 3.13, and perhaps a bit beyond.

**Comment by zzzeek** [comment]
oh the function was private, in that case yes we might want to just vendor it hoping it's not a very long function

**Comment by zzzeek** [comment]
yes we are keeping 1.4 around longer than usual for sure.   but it's going to have to stop at some point, it's still supporting python 2.7 and every release of it has to work on 2.7

**Comment by sqla-tester** [comment]
**Benjamin A. Beasley** has proposed a fix for this issue in the **rel_1_4** branch:

**SQLAlchemy 1.4: Fix building the C extension on Python 3.13** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5339

**Comment by zzzeek** [comment]
fixed in fc66fda85e30718a384e9d214b927842cbc7d442
