### ISSUE TITLE
Hybrid Property error when using sql.func return introduced in 1.4

### ISSUE THREAD

**Issue by TheKigen** [sqlalchemy/sqlalchemy#6401]
**Describe the bug**
So on 1.3 and earlier versions of Sqlalchemy we were using a hybrid_property to return an sql.func.tstzrange return.  On 1.4 it now causes an AttributeError.

**Expected behavior**
I expected it to work correctly as it did in Sqlalchemy 1.3.

**To Reproduce**
```py
import datetime
from contextlib import contextmanager
from sqlalchemy import Column, Integer, DateTime, Interval
from sqlalchemy.engine import create_engine
from sqlalchemy.ext.hybrid import hybrid_property
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from sqlalchemy.sql import func


Base = declarative_base()


class TestTimeRange(Base):
    __tablename__ = 'test_time_range'
    id = Column(Integer, primary_key=True)
    start_time = Column(DateTime(timezone=True), nullable=False)
    duration = Column(Interval, nullable=False)

    @hybrid_property
    def end_time(self):
        return self.start_time + self.duration

    @hybrid_property
    def time_range(self):
        return func.tstzrange(self.start_time, self.end_time + datetime.timedelta(seconds=1))


engine = create_engine('postgresql://devtest:devtest@localhost/devtest')
Base.metadata.create_all(engine)

Session = sessionmaker(bind=engine)


@contextmanager
def session_scope():
    session = Session()
    try:
        yield session
        session.commit()
    except:
        session.rollback()
        raise
    finally:
        session.close()


with session_scope() as session:
    session.query(TestTimeRange).delete()
    session.commit()

with session_scope() as session:
    test_time_range = TestTimeRange()
    test_time_range.start_time = datetime.datetime.utcnow()
    test_time_range.duration = datetime.timedelta(minutes=1, seconds=30)
    session.add(test_time_range)
    session.commit()

with session_scope() as session:
    query = session.query(TestTimeRange.id, TestTimeRange.time_range)
    print(query.count())

```

**Error**

```
(venv) C:\Users\Max\Desktop\Coding\Python\dev>python test_sqlalchemy_hybrid.py
Traceback (most recent call last):
  File "test_sqlalchemy_hybrid.py", line 63, in <module>
    print(query.count())
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\orm\query.py", line 3078, in count
    return self._from_self(col).enable_eagerloads(False).scalar()
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2819, in scalar
    ret = self.one()
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2796, in one
    return self._iter().one()
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2837, in _iter
    execution_options={"_sa_orm_load_options": self.load_options},
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1670, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1521, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 314, in _execute_on_connection
    self, multiparams, params, execution_options
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1388, in _execute_clauseelement
    linting=self.dialect.compiler_linting | compiler.WARN_LINTING,
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 541, in _compile_w_cache
    **kw
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 570, in _compiler
    return dialect.statement_compiler(dialect, self, **kw)
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\compiler.py", line 766, in __init__
    Compiled.__init__(self, dialect, statement, **kwargs)
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\compiler.py", line 455, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\compiler.py", line 490, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\visitors.py", line 81, in _compiler_dispatch
    return meth(self, **kw)
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\compiler.py", line 2981, in visit_select
    select_stmt, self, **kwargs
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\base.py", line 501, in create_for_statement
    return klass.create_for_statement(statement, compiler, **kw)
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\orm\context.py", line 601, in create_for_statement
    self._setup_for_generate()
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\orm\context.py", line 696, in _setup_for_generate
    entity.setup_compile_state(self)
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\orm\context.py", line 2637, in setup_compile_state
    column = current_adapter(self.column, False)
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\orm\context.py", line 1189, in _adapt_clause
    return visitors.replacement_traverse(clause, {}, replace)
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\visitors.py", line 808, in replacement_traverse
    obj, deferred_copy_internals=deferred_copy_internals, **opts
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\visitors.py", line 786, in clone
    newelem = replace(elem)
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\orm\context.py", line 1185, in replace
    e = adapter(elem)
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\util.py", line 900, in replace
    return self._corresponding_column(col, True)
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\util.py", line 834, in _corresponding_column
    col, require_embedded=require_embedded
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\selectable.py", line 235, in corresponding_column
    return self.exported_columns.corresponding_column(
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\selectable.py", line 727, in exported_columns
    return self.columns
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1093, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\selectable.py", line 746, in columns
    self._populate_column_collection()
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\selectable.py", line 1617, in _populate_column_collection
    self.element._generate_fromclause_column_proxies(self)
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\selectable.py", line 704, in _generate_fromclause_column_proxies
    col._make_proxy(fromclause) for col in self.c
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 1093, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\selectable.py", line 746, in columns
    self._populate_column_collection()
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\selectable.py", line 1617, in _populate_column_collection
    self.element._generate_fromclause_column_proxies(self)
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\selectable.py", line 5768, in _generate_fromclause_column_proxies
    for name, c, repeated in self._generate_columns_plus_names(False):
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\selectable.py", line 5752, in _generate_columns_plus_names
    return [name_for_col(c) for c in cols]
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\sql\selectable.py", line 5752, in <listcomp>
    return [name_for_col(c) for c in cols]
  File "C:\Users\Max\Desktop\Coding\Python\dev\venv\lib\site-packages\sqlalchemy\orm\context.py", line 799, in exported_columns_iterator
    "entity_namespace"
AttributeError: 'HasEntityNamespace' object has no attribute '_all_column_expressions'
```

**Versions.**
 - OS: Windows 10 and Ubuntu 18.04
 - Python: 3.6
 - SQLAlchemy: 1.4.11
 - Database: PostgreSQL 12
 - DBAPI: psycopg2

**Additional context**
This works fine on Sqlalchemy 1.3.
```
(venv) C:\Users\Max\Desktop\Coding\Python\dev>pip install sqlalchemy==1.3.24
Collecting sqlalchemy==1.3.24
  Downloading SQLAlchemy-1.3.24-cp36-cp36m-win_amd64.whl (1.2 MB)
     |████████████████████████████████| 1.2 MB 6.4 MB/s
Installing collected packages: sqlalchemy
  Attempting uninstall: sqlalchemy
    Found existing installation: SQLAlchemy 1.4.11
    Uninstalling SQLAlchemy-1.4.11:
      Successfully uninstalled SQLAlchemy-1.4.11
Successfully installed sqlalchemy-1.3.24

(venv) C:\Users\Max\Desktop\Coding\Python\dev>python test_sqlalchemy_hybrid.py
1
```

**Have a nice day!**

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**accommodate HasEntityNamespace in context.all_selected_columns** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2790

**Comment by zzzeek** [comment]
thanks for reporting
