### ISSUE TITLE
SQLAlchemy v2.x: URL.normalized_query throws AttributeError (while v1.4x did not)

### ISSUE THREAD

**Issue by davidandreoletti** [sqlalchemy/sqlalchemy#9682]
### Describe the bug

We are upgrading a code base from SQLALchemy v1.4x to v2.x. 

On v1.4, URL.normalized_query would return a dictionary as stated by the official documentation.
On v2.x, URL.normalized_query throws `{AttributeError}AttributeError("'URL' object has no attribute '__dict__'")`. The error is raised in the memoized helper function.

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/core/engines.html#sqlalchemy.engine.URL.normalized_query

### SQLAlchemy Version in Use

2.0.9

### DBAPI (i.e. the database driver)

asyncpg

### Database Vendor and Major Version

Postgres 14

### Python Version

3.10

### Operating system

Linux

### To Reproduce

```python
uri = make_url("postgresql://test:something@127.0.0.1:5432/tests?schema=public")
data = uri.normalized_query
```

### Error

```
Traceback (most recent call last):
  File "/Users/me/Documents/Developments/TMP_WORKSPACES/myproject/action.git/action/database/sqlalchemy/sqlalchemy.py", line 375, in __migrate
    await self._migrate(instance=instance, options=options)
  File "/Users/me/Documents/Developments/TMP_WORKSPACES/myproject/action.git/action/database/sqlalchemy/sqlalchemypostgresql.py", line 217, in _migrate
    db_schema = (uri.normalized_query or {}).get("schema", None)
  File "/Users/me/.pyenv/versions/action_py310_0/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 1138, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
AttributeError: 'URL' object has no attribute '__dict__'
```

### Additional context

None

**Comment by CaselIT** [comment]
Hi,

Thanks for reporting.
It seems there aren't any test about this method and very few people use it.

It's also strange that this is working on 1.4 since URL is a named tuple in it too, and it seems to the same memoization decorator.
Trying it seems that in 1.4 URL continues to have __dict__, not sure why

**Comment by CaselIT** [comment]
Well the `__dict__` thing is obvious, in 1.4 URL was a namedtuple subclass, in 2.0 it *is* a named tuple

**Comment by sqla-tester** [comment]
**Federico Caselli** has proposed a fix for this issue in the **main** branch:

**Fixed bug in `URL.normalized_query`** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4579
