### ISSUE TITLE
Reflection Redshift Table with Unique-Constraint causes Error

### ISSUE THREAD

**Issue by SebastianSchroeder** [sqlalchemy/sqlalchemy#7730]
### Describe the bug

We are upgrading from 1.4 from 1.3 and are stuck with an error which happens when we reflect a Table which has a unique constraint. This worked fine on 1.3.

We traced the error to sqlalchemy/dialects/postgresql/base.py:4234

``` python
idx_keys = idx_key.split()
```

Which is called from sqlalchemy/engine/reflection.py:806

``` python
self._reflect_indexes(
            table_name,
            schema,
            table,
            cols_by_orig_name,
            include_columns,
            exclude_columns,
            reflection_options,
        )
```

It seems that the unique constraint is picked up as an index and not as a unique constraint.

Here is the DDL of the table:
```SQL
create table if not exists demo_schema.table_with_unique_constraint
(
    id                   varchar(255) default '-1'::character varying not null encode zstd,
    other_id     varchar(50)                                  not null encode zstd distkey
        primary key
        constraint unq_other_id
            unique,
    name                 varchar(255) encode zstd
)
    diststyle key
    sortkey (other_id);
```

### To Reproduce

```python
con_string = f"postgresql+psycopg2://{username}:{quote(password, safe='')}@{host}:{port}/{database}"
engine = create_engine(con_string, connect_args={'sslmode': 'require'})

with engine.connect() as connection:
  md = MetaData(schema='demo_schema')
  table = Table('table_with_unique_constraint', md, autoload_with=connection)
```

### Error

```
Error
Traceback (most recent call last):
AttributeError: 'NoneType' object has no attribute 'split'
``` 

### Versions

- OS: macOS 12.2.1
- Python: 3.8
- SQLAlchemy: 1.4.31
- Database: Redshift (PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.35480)
- DBAPI: psycopg2 (2.9.3)

**Comment by SebastianSchroeder** [comment]
We are using psycopg2 and the postgresql dialect to connect to Redshift.

The Stacktrace is swallowed somewhere during exception propagation. Here is what I could extract with PyCharm.

```
Stack:
	get_indexes, base.py:4234
	cache, reflection.py:55
	<frame not available>
	get_indexes, reflection.py:605
	_reflect_indexes, reflection.py:1025
	reflect_table, reflection.py:806
	_autoload, schema.py:712
	_init, schema.py:677
	__new__, schema.py:602
	warned, deprecations.py:309
	<frame not available>
	test_alchemy_error, datavault_test.py:34
	_callTestMethod, case.py:633
	run, case.py:676
	__call__, case.py:736
	run, suite.py:122
	__call__, suite.py:84
	run, suite.py:122
	__call__, suite.py:84
	run, runner.py:176
	run, unittestpy.py:310
	runTests, main.py:271
	__init__, main.py:101
	<module>, _jb_unittest_runner.py:35
```

**Comment by zzzeek** [comment]
can you try running your program from the command line so that a proper stack trace is generated?  the above is not usable.

**Comment by CaselIT** [comment]
> We are using psycopg2 and the postgresql dialect to connect to Redshift.

The internal postgresql dialect does not support Redshift and is not tested against it, so it may break in unexpected ways.

Please use the external dialect https://pypi.org/project/sqlalchemy-redshift/

**Comment by SebastianSchroeder** [comment]
Using the redshift dialect fixed the problem! Thanks.
