### ISSUE TITLE
Simple Join That Works in 1.3.x Raises InvalidRequestError in 1.4.x

### ISSUE THREAD

**Issue by nuthanmunaiah** [sqlalchemy/sqlalchemy#6092]
**Describe the bug**

A simple query with a join between two tables that works in SQLAlchemy 1.3.x raises an `InvalidRequestError` in 1.4.x. See _additional context_ for the output with SQLAlchemy 1.3.x. Although the error message (`... 'User' has no attribute 'product'`) is factually accurate, according to the [documentation](https://docs.sqlalchemy.org/en/14/orm/query.html#sqlalchemy.orm.Query.filter_by) `filter_by` is supposed to use _"The keyword expressions ... [from] ... the last entity that was the target of a call to Query.join()"_.

Query in question is shown below.

```py
user = session.query(User) \
    .filter_by(name='John Smith') \
    .filter_by(email='john.smith@email.com') \
    .join(Order) \
    .filter_by(product='Socks') \
    .filter_by(timestamp=1616086530)
```

**Expected behavior**

The script (`main.py` included below) produces the output shown below.

```console
$ python main.py
VERSION   1.4.1
QUERY     SELECT user.id AS user_id, user.name AS user_name, user.email AS user_email
          FROM user JOIN "order" ON user.id = "order".user_id
          WHERE user.name = ? AND user.email = ? AND "order".product = ? AND "order".timestamp = ?
RESULT    1|John Smith|john.smith@email.com
```

**To Reproduce**

Unzip the SQLite database files in [orders.zip](https://github.com/sqlalchemy/sqlalchemy/files/6166144/orders.zip) as `orders.db` before attempting to run the `main.py` file shown below.

```py
# main.py
import sqlalchemy
from sqlalchemy import create_engine, Column, ForeignKey, Integer, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, sessionmaker

Base = declarative_base()

class User(Base):
    __tablename__ = 'user'

    id = Column(Integer, primary_key=True)
    name = Column(String(125))
    email = Column(String(125))

    def __str__(self):
        return f'{self.id}|{self.name}|{self.email}'


class Order(Base):
    __tablename__ = 'order'

    id = Column(Integer, primary_key=True)
    product = Column(String(40))
    timestamp = Column(Integer)

    user_id = Column(Integer, ForeignKey('user.id'), nullable=False)

    def __str__(self):
        return f'{self.id}|{self.product}|{self.timestamp}|{self.user_id}'


def main():
    engine = create_engine('sqlite+pysqlite:///orders.db')
    Session = sessionmaker(engine)
    session = Session()
    try:
        print(f'VERSION   {sqlalchemy.__version__}')
        user = session.query(User) \
            .filter_by(name='John Smith') \
            .filter_by(email='john.smith@email.com') \
            .join(Order) \
            .filter_by(product='Socks') \
            .filter_by(timestamp=1616086530)
        query = str(user).replace('\n', '\n          ')
        print(f'QUERY     {query}')
        print(f'RESULT      {user.one_or_none()}')
    finally:
        session.close()


if __name__ == '__main__':
    main()
```

**Error**

```console
$ python main.py
VERSION   1.4.1
Traceback (most recent call last):
  File "/home/user/sqlalchemy/.venv/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 1580, in _entity_namespace_key
    return getattr(ns, key)
AttributeError: type object 'User' has no attribute 'product'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 52, in <module>
    main()
  File "main.py", line 42, in main
    .filter_by(product='Socks') \
  File "/home/user/sqlalchemy/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 1723, in filter_by
    for key, value in kwargs.items()
  File "/home/user/sqlalchemy/.venv/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 1723, in <listcomp>
    for key, value in kwargs.items()
  File "/home/user/sqlalchemy/.venv/lib/python3.7/site-packages/sqlalchemy/sql/base.py", line 1587, in _entity_namespace_key
    replace_context=err,
  File "/home/user/sqlalchemy/.venv/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 198, in raise_
    raise exception
sqlalchemy.exc.InvalidRequestError: Entity namespace for "user" has no property "product"
```

**Versions.**
 - OS: `Ubuntu 18.04.5 LTS`
 - Python: `Python 3.7.2`
 - SQLAlchemy: `1.4.1`
 - Database: `SQLite 3.33.0 2020-08-14 13:23:32 fca8dc8b578f215a969cd899336378966156154710873e68b3d9ac5881b0alt2`
 - DBAPI: `sqlite3 2.6.0`

**Additional context**

```console
$ python main.py
VERSION   1.3.23
QUERY     SELECT user.id AS user_id, user.name AS user_name, user.email AS user_email
          FROM user JOIN "order" ON user.id = "order".user_id
          WHERE user.name = ? AND user.email = ? AND "order".product = ? AND "order".timestamp = ?
RESULT    1|John Smith|john.smith@email.com
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**repair legacy_last_joined_entity for no onclause** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2651

**Comment by zzzeek** [comment]
workaround for now if you can't wait for 1.4.2, add the ON clause  join(Order, Order.user_id == User.id).

**Comment by nuthanmunaiah** [comment]
Cheers. Thanks so much for the quick resolution. I will hold off on upgrading to 1.4.x until 1.4.2 is released.
