### PR TITLE
Fix missing class attributes when using __class_getitem__

### LINKED ISSUE #7462: Copied __class_getitem__  in declarative Base class forgets attributes
### Describe the bug

I guess this is caused by https://github.com/sqlalchemy/sqlalchemy/pull/7381. When using it, all other attributes, e.g. `__table__` are forgotten by the table.

### To Reproduce

```python
T = TypeVar("T", bound="CommonBase")  # noqa

class CommonBase(Generic[T]):
	@classmethod
	def boring(cls: Type[T]) -> Type[T]:
		return cls

@as_declarative()
class Base(CommonBase[T]):
	pass

class Tab(Base["Tab"]):
       __tablename__ = "foo"
	a = Column(Integer, primary_key=True)

assert Tab.__table__
```

### Error

AttributeError: type object 'CommonBase' has no attribute '__table__'

### Versions

OS: Linux
Python: 3.7.1
SQLAlchemy: 1.4.28

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kasium**
Closes #7462

### Description
As discussed in #7462, the normal `__class_getitem__` of `typing.Generics` leads to issues, so that the metaclass of the declarative base is not applied to child classes of it. Therefore we replace it with an own imlementation.

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [X] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

File: lib/sqlalchemy/orm/decl_api.py [hunk 1]
```diff
@@ -788,7 +788,7 @@ class Base(metaclass=DeclarativeMeta):
         if mapper:
             class_dict["__mapper_cls__"] = mapper
         if hasattr(cls, "__class_getitem__"):
-            class_dict["__class_getitem__"] = cls.__class_getitem__
+            class_dict["__class_getitem__"] = lambda cls, _: cls
```
Comment (CaselIT) [inline lib/sqlalchemy/orm/decl_api.py:791]: just to be more naming and introspection friently we could define an actual fn
```py
def __class_getitem__(cls, key):
    return cls
```

**Review by CaselIT — APPROVED** [review]
thanks. will bring this in gerrit

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **CaselIT** to try to get revision d5e5765e0e5542149f116ed9ccff1b3e2e32dee5 of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change d5e5765e0e5542149f116ed9ccff1b3e2e32dee5: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3417

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3417 has been **merged**. Congratulations! :)

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3428 has been **merged**. Congratulations! :)
