### ISSUE TITLE
v1.4.x potential bug; as_scalar support dropped without deprecation

### ISSUE THREAD

**Issue by jvanasco** [sqlalchemy/sqlalchemy#4854]
I accidentally ran a test suite in an environment I had the SqlAlchemy master running on, and an UPDATE which works on at-least 1.2 and 1.3 branches failed.  This error was inconsistent with the behavior expected in https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#change-f413ff8c13a1fb7d766bfa16dfcdfbf1 ; I believe this may be linked to #4617.  However, I think this exception is more likely due to me mixing the ORM and core in a way that worked (was it supposed to?), but no longer does (is it supposed to?).

SqlAlchemy raises an Exception:

    AttributeError: 'Subquery' object has no attribute 'as_scalar'

Looking at the migration guide though, I tried the new API and...

    AttributeError: 'Subquery' object has no attribute 'scalar_subquery'

The code to illustrate below, I can generate a test case to reproduce if need.

```
    _q_sub = (
        dbSession.query(models.MyTable.id)
            .order_by(models.MyTable.id.desc())
            .limit(1)
            .subquery()
            .as_scalar()  # also fails as `.scalar_subquery()`
    )
    dbSession.execute(
        models.MyTable2.__table__.update().values(
            mytable_id=_q_sub
        )
    )
```

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Restore subquery.as_scalar() w/ deprecation** https://gerrit.sqlalchemy.org/1460

**Comment by zzzeek** [comment]
if you can just review what I'm doing there that would be helpful.

**Comment by jvanasco** [comment]
Thanks, Mike. 

This looks good and passes.  I apologize for an error in my report too, I had followed the instructions on the changelog and made this substitution

          .subquery()
        - .as_scalar()
        + .scalar_subquery()

instead of doing the following, which makes more sense:

        - .subquery()
        - .as_scalar()
        + .scalar_subquery()

which is also what you now recommend in the docstring,.

The only suggestion I have: can that docstring you included in the selectable source code be added into that changelog text?

**Comment by zzzeek** [comment]
which changelog text

**Comment by zzzeek** [comment]
the 1.4 changelog note?   it's so long -winded already do we need a bullet list

**Comment by jvanasco** [comment]
this note:

https://docs.sqlalchemy.org/en/14/changelog/changelog_14.html#change-f413ff8c13a1fb7d766bfa16dfcdfbf1

it's the one that addresses the changes to `as_scalar` and `scalar_subquery`

> The SelectBase.as_scalar() and Query.as_scalar() methods have been renamed to SelectBase.scalar_subquery() and Query.scalar_subquery(), respectively. The old names continue to exist within 1.4 series with a deprecation warning. In addition, the implicit coercion of SelectBase, Alias, and other SELECT oriented objects into scalar subqueries when evaluated in a column context is also deprecated, and emits a warning that the SelectBase.scalar_subquery() method should be called explicitly. This warning will in a later major release become an error, however the message will always be clear when SelectBase.scalar_subquery() needs to be invoked. The latter part of the change is for clarity and to reduce the implicit decisionmaking by the query coercion system.
> 
> This change is part of the larger change to convert select() objects to no longer be directly part of the “from clause” class hierarchy, which also includes an overhaul of the clause coercion system.
> 
> References: #4617

Indeed it is long.  i could take a stab at reformatting it if you'd like
