### ISSUE TITLE
query.from_statement(...).all() fails for many to many relationship with lazy="subquery"

### ISSUE THREAD

**Issue by baarney** [sqlalchemy/sqlalchemy#7505]
### Describe the bug

I came across this whilst upgrading some old code from 1.3.23 with mysql to 1.4.29 with mariadb.

If I query a table which has a many to many relationship via a secondary table:
- Using lazy="subquery" on the relationship
- Using a text SQL statement

Then the code throws an exception:

`AttributeError: type object 'ORMFromStatementCompileState' has no attribute '_create_entities_collection'`

Note that both of these conditions have to be true:
- Using any other lazy loading strategy works.
- Using object (non text) query works

It looks like that in this case one of the internal queries creates a `ORMFromStatementCompileState` instead of a `ORMSelectCompileState`, which indeed does not contain the `_create_entities_collection`.

Simple work-around for me was to replace "subquery" with "selectin", which is probably a better solution anyway.

### To Reproduce

```python
from sqlalchemy import create_engine, Column, ForeignKey, Integer, String, text, Table
from sqlalchemy.orm import declarative_base, relationship, sessionmaker

engine = create_engine('sqlite://')

Base = declarative_base()

# data model

foo_bar = Table('foo_bar', Base.metadata,
    Column('foo_id', ForeignKey('foo.id'), primary_key=True),
    Column('bar_id', ForeignKey('bar.id'), primary_key=True)
)

class Foo(Base):
    __tablename__ = 'foo'
    id = Column(Integer, primary_key=True)
    name = Column(String)

    # using lazy='subquery' fails with text statement - any other option works
    # - dynamic, joined, select, subquery, selectin
    bars = relationship("Bar", secondary=foo_bar, lazy='subquery')

    def __repr__(self):
        return "<Foo: '%s', bars='%s'>" % (self.name, self.bars)


class Bar(Base):
    __tablename__ = 'bar'
    id = Column(Integer, primary_key=True)
    name = Column(String)

    def __repr__(self):
        return "<Bar: '%s'>" % self.name


Base.metadata.create_all(engine)

# add data

Session = sessionmaker(bind=engine)
session = Session()

foo1 = Foo(name='Foo 1')
foo2 = Foo(name='Foo 2')
bar1 = Bar(name='Bar 1')
bar2 = Bar(name='Bar 2')

foo1.bars = [bar1, bar2]
foo2.bars = [bar1, bar2]

session.add_all([foo1, foo2])
session.commit()

# query via objects - works in all cases
print('---- query ----')
query = session.query(Foo)
items = query.all()
for item in items:
    print(item)

# query via statement - fails when lazy='subquery'
print('---- statement ----')
stmt = text('select * from foo')
query = session.query(Foo).from_statement(stmt)
items = query.all()
for item in items:
    print(item)
```

### Error

```
AttributeError: type object 'ORMFromStatementCompileState' has no attribute '_create_entities_collection'

_setup_query_from_rowproc, strategies.py:1712
create_row_processor, strategies.py:1821
create_row_processor, interfaces.py:658
_instance_processor, loading.py:796
row_processor, context.py:2537
<listcomp>, loading.py:70
instances, loading.py:69
orm_setup_cursor_result, context.py:353
execute, session.py:1695
_iter, query.py:2894
all, query.py:2759
<module>, test_query_stmt.py:56
``` 

### Versions

- OS: Linux
- Python: 3.9.9
- SQLAlchemy: 1.4.29
- Database: sqlite and/or mariadb
- DBAPI: mariadb 1.0.9

### Additional context

I found this upgrading a Flask-SQLAlchemy app but I removed the Flask parts for the simplified example above.

I believe this worked in SQLALchemy 1.3.23 with mysql but I no longer have that environment to verify.

**Comment by CaselIT** [comment]
Hi,

Thanks for the report and the reproducing script

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**rudimental support for subqueryload w/ from_statement** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3431

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **rel_1_4** branch:

**rudimental support for subqueryload w/ from_statement** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/3432

**Comment by zzzeek** [comment]
OK I can fix part of this but the part that's using text() explicitly, i think we can't support that right now.  from_statement(select()) will still work.   i will have this raise an explicit message assuming this is the case.

**Comment by zzzeek** [comment]
oh OK, yes you have to do this.  this is at least somewhat workable.

    stmt = text('select * from foo').columns(Foo.id, Foo.name)

will have the error indicate this.

**Comment by zzzeek** [comment]
OK, new approach again, I think what 1.3 is doing is that in a from_statement() load, incompatible loader strategies like joinedload() and subqueryload() are just skipped, silently.  your query above does a lazyload for those extra items.    there's no quick way to get a text() statement to work correctly with subqueryloading so i will just restore 1.3's behavior for this instead.   selectinload() continues to work in all cases and should pretty much always be chosen over subqueryload().

**Comment by baarney** [comment]
Awesome. I'll stick with the change to `selectin` for my problem, but turning the bug around that quickly is fantastic work!
