### ISSUE TITLE
pymssql might support native UUID, set attribute

### ISSUE THREAD

**Issue by SimonKenoby** [sqlalchemy/sqlalchemy#9414]
### Describe the bug

Hi, 

We are currently in the process of moving from SQLAlchemy 1.4 to 2.0. We were using UUID type from [sqlalchemy-utils](https://sqlalchemy-utils.readthedocs.io/en/latest/_modules/sqlalchemy_utils/types/uuid.html). As there is a uuid type in sqlalchemy 2.0, I tried to use it. 

Insert works well and the db is up to date, but I encounter an issue while doing a select base on that id. (same error as this one: https://github.com/sqlalchemy/sqlalchemy/issues/7225) . 

Documentation suggest that it supports vendor specific uuid types, so I guessed this should work as well. 

It doesn't look like a migration issue, as I was able to reproduce the problem with a new table using new code. 

Any suggestion is welcomed :) 

Thanks,
Simon.  

### Optional link from https://docs.sqlalchemy.org which documents the behavior that is expected

https://docs.sqlalchemy.org/en/20/core/type_basics.html#sqlalchemy.types.Uuid

### SQLAlchemy Version in Use

2.0.4

### DBAPI (i.e. the database driver)

pymysql

### Database Vendor and Major Version

ms sql 14.0.2042.3 Enterprise Edition (64-bit) Windows Server 2016 Standard 10.0

### Python Version

3.10

### Operating system

WSL + docker on windows. 

### To Reproduce

```python
from uuid import uuid4
from sqlalchemy import Column, Integer, Uuid, create_engine, select
from sqlalchemy.orm import declarative_base, Session


Base = declarative_base()

class Estimation(Base):
    """Stats about a translation task."""

    __tablename__ = "test_table"
    id = Column(Uuid(native_uuid=True), primary_key=True)
    score = Column(Integer)


engine = create_engine("mssql+pymssql://[my-url]")

Base.metadata.create_all(engine)
my_id = uuid4()
with Session(engine) as session:
    estimation = Estimation(id=my_id)
    session.add(estimation)
    session.commit()

with Session(engine) as session:
    stmt = select(Estimation).where(Estimation.id==my_id)
    estimation = session.execute(stmt).first()
    print(estimation)
    estimation.score = 5
    session.add(estimation)
    session.commit()
```

### Error

```
Traceback (most recent call last):
  File "/mnt/c/projects/mtme/sql.py", line 27, in <module>
    estimation = session.execute(stmt).first()
  File "/home/lorensi/miniconda3/envs/lorensi/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 1397, in first
    return self._only_one_row(
  File "/home/lorensi/miniconda3/envs/lorensi/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 732, in _only_one_row
    row: Optional[_InterimRowType[Any]] = onerow(hard_close=True)
  File "/home/lorensi/miniconda3/envs/lorensi/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 2252, in _fetchone_impl
    row = next(self.iterator, _NO_ROW)
  File "/home/lorensi/miniconda3/envs/lorensi/lib/python3.10/site-packages/sqlalchemy/orm/loading.py", line 190, in chunks
    fetch = cursor._raw_all_rows()
  File "/home/lorensi/miniconda3/envs/lorensi/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 521, in _raw_all_rows
    return [make_row(row) for row in rows]
  File "/home/lorensi/miniconda3/envs/lorensi/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 521, in <listcomp>
    return [make_row(row) for row in rows]
  File "lib/sqlalchemy/cyextension/resultproxy.pyx", line 24, in sqlalchemy.cyextension.resultproxy.BaseRow.__init__
  File "/home/lorensi/miniconda3/envs/lorensi/lib/python3.10/site-packages/sqlalchemy/sql/sqltypes.py", line 3633, in process
    value = _python_UUID(value)
  File "/home/lorensi/miniconda3/envs/lorensi/lib/python3.10/uuid.py", line 174, in __init__
    hex = hex.replace('urn:', '').replace('uuid:', '')
AttributeError: 'UUID' object has no attribute 'replace'
```

**Comment by zzzeek** [comment]
hi - 

can you confirm this fixes the issue

```py
engine = create_engine("mssql+pymssql://[my-url]")
engine.dialect.supports_native_uiuid = True

# .. rest of program

```

this would be the patch, test support is already present, we just dont test pymssql on this end 

```diff
diff --git a/lib/sqlalchemy/dialects/mssql/pymssql.py b/lib/sqlalchemy/dialects/mssql/pymssql.py
index 699f61714b..b23c7bbc3a 100644
--- a/lib/sqlalchemy/dialects/mssql/pymssql.py
+++ b/lib/sqlalchemy/dialects/mssql/pymssql.py
@@ -51,6 +51,7 @@ class MSIdentifierPreparer_pymssql(MSIdentifierPreparer):
 class MSDialect_pymssql(MSDialect):
     supports_statement_cache = True
     supports_native_decimal = True
+    supports_native_uuid = True
     driver = "pymssql"
 
     preparer = MSIdentifierPreparer_pymssql

```

**Comment by SimonKenoby** [comment]
Hi, thanks for quick reply. It looks like to have partially solved the problem, I now get

`Traceback (most recent call last):
  File "/mnt/c/projects/mtme/sql.py", line 30, in <module>
    estimation.score = 5
  File "/home/lorensi/miniconda3/envs/lorensi/lib/python3.10/site-packages/sqlalchemy/engine/row.py", line 86, in __setattr__
    raise AttributeError("can't set attribute")
AttributeError: can't set attribute`

But I think this is unrelated.

**Comment by zzzeek** [comment]
looks like code that wants to assign a value to a Row which wont work (didnt think that worked in 1.4 either..)

**Comment by zzzeek** [comment]
im doing this now, in case you were starting a PR, need to get pymssql back in CI

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**audition pymssql once more; retire sane_rowcount_returning** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4487

**Comment by zzzeek** [comment]
this went into non-related rabbit holes as well, but the end result should be good
