### PR TITLE
SQLAlchemy 1.4: Fix building the C extension on Python 3.13

### PR DESCRIPTION
**Pull request by musicinmybrain**
### Description

The C extension for SQLAlchemy 1.4 uses `_PyArg_NoKeywords()`, an undocumented private API that [was moved to the `pycore_modsupport.h` internal C API in Python 3.13](https://github.com/python/cpython/issues/110964).

As a result, the C extension fails to build on Python 3.13:

```
  lib/sqlalchemy/cextension/resultproxy.c: In function ‘tuplegetter_new’:
  lib/sqlalchemy/cextension/resultproxy.c:831:10: error: implicit declaration of function ‘_PyArg_NoKeywords’ [-Wimplicit-function-declaration]
    831 |     if (!_PyArg_NoKeywords("tuplegetter", kwds))
        |          ^~~~~~~~~~~~~~~~~
```

This was reported as https://github.com/sqlalchemy/sqlalchemy/issues/11499.

This PR proposes to fix that by adding a `static` function wrapper that calls `_PyArg_NoKeywords` on Python 3.12 and older, and imitates [its implementation](https://github.com/python/cpython/blob/3a83b172af1bde6032ecca7c1a2e6b82d06325e1/Python/getargs.c#L2839-L2861) on Python 3.13 and later.

### Checklist

This pull request is:

- [ ] A documentation / typographical / small typing error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

-----

Compilation can be easily tested in a virtualenv:

```
$ python3.13 -m venv _e
(_e) $ pip install build
(_e) $ REQUIRE_SQLALCHEMY_CEXT=1 python -m build
```

Actually running the test suite is a bit harder, since the version of `greenlet` on PyPI still doesn’t build on Python 3.13.

I tested this as a patch for [the `python-sqlalchemy1.4` compat package in Fedora Rawhide](https://src.fedoraproject.org/rpms/python-sqlalchemy1.4) and found that the C extension compiled and almost all of the tests passed. There were a few failures I haven’t investigated closely yet,

```
FAILED test/orm/test_mapper.py::MapperTest::test_synonym_nonexistent_attr - A...
FAILED test/ext/test_serializer.py::ColumnPropertyWParamTest::test_deserailize_colprop
FAILED test/ext/test_serializer.py::SerializeTest::test_aliases - AttributeEr...
FAILED test/ext/test_serializer.py::SerializeTest::test_annotated_one - Attri...
FAILED test/ext/test_serializer.py::SerializeTest::test_any - AttributeError:...
FAILED test/ext/test_serializer.py::SerializeTest::test_attribute - Attribute...
FAILED test/ext/test_serializer.py::SerializeTest::test_columns - AttributeEr...
FAILED test/ext/test_serializer.py::SerializeTest::test_expression - Attribut...
FAILED test/ext/test_serializer.py::SerializeTest::test_mapper - AttributeErr...
FAILED test/ext/test_serializer.py::SerializeTest::test_orm_join - AttributeE...
FAILED test/ext/test_serializer.py::SerializeTest::test_query_one - Attribute...
FAILED test/ext/test_serializer.py::SerializeTest::test_query_three - Attribu...
FAILED test/ext/test_serializer.py::SerializeTest::test_query_two - Attribute...
FAILED test/ext/test_serializer.py::SerializeTest::test_tables - AttributeErr...
FAILED test/ext/test_serializer.py::SerializeTest::test_unicode - AttributeEr...
========= 15 failed, 15198 passed, 2407 skipped in 1336.48s (0:22:16) ==========
```

with tracebacks like

```
  File "/builddir/build/BUILD/python-sqlalchemy1.4-1.4.52-build/SQLAlchemy-1.4.52/lib/sqlalchemy/ext/serializer.py", line 174, in dumps
    pickler = Serializer(buf, protocol)
  File "/builddir/build/BUILD/python-sqlalchemy1.4-1.4.52-build/SQLAlchemy-1.4.52/lib/sqlalchemy/ext/serializer.py", line 113, in Serializer
    pickler.persistent_id = persistent_id
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_pickle.Pickler' object attribute 'persistent_id' is read-only
```

but these also failed when the C extension was *not* built, so they must represent a separate issue unrelated to this PR.

### CODE REVIEW

**Comment by musicinmybrain** [comment]
> ```
>   File "/builddir/build/BUILD/python-sqlalchemy1.4-1.4.52-build/SQLAlchemy-1.4.52/lib/sqlalchemy/ext/serializer.py", line 174, in dumps
>     pickler = Serializer(buf, protocol)
>   File "/builddir/build/BUILD/python-sqlalchemy1.4-1.4.52-build/SQLAlchemy-1.4.52/lib/sqlalchemy/ext/serializer.py", line 113, in Serializer
>     pickler.persistent_id = persistent_id
>     ^^^^^^^^^^^^^^^^^^^^^
> AttributeError: '_pickle.Pickler' object attribute 'persistent_id' is read-only
> ```

It looks like this requires a backport of (at least part of) https://github.com/sqlalchemy/sqlalchemy/commit/754804635bc922c20d0b0075e0ed2da0add38742.

**Comment by zzzeek** [comment]
oh, well yah it looks like i wasnt targeting 1.4 for 3.13 at all, so yes based on what i said above we have to backport all of that to 1.4 as well

**Comment by musicinmybrain** [comment]
> oh, well yah it looks like i wasnt targeting 1.4 for 3.13 at all, so yes based on what i said above we have to backport all of that to 1.4 as well

I’m not prepared to backport all the tox fixes, but in case it helps, I backported just the code fixes in https://github.com/musicinmybrain/sqlalchemy/commit/5e7446a95e614e680c46e971f61ff9b5c794ee51, and I can confirm that this sufficed to get all the tests passing on Python 3.13 in the Fedora package.

**Comment by zzzeek** [comment]
OK for the backport of that other stuff, me or @CaselIT should make separate gerrits for that on our end, move the changelog, and do it like that

**Comment by zzzeek** [comment]
this is ongoing at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5342 , also adding greenlet test for py313 in https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5343

**Review by sqla-tester — COMMENTED** [review]
OK, this is **sqla-tester** setting up my work on behalf of **zzzeek** to try to get revision 8a5888b147022b4586d30dcd7159e4fa6a31ec0e of this pull request into gerrit so we can run tests and reviews and stuff

**Comment by sqla-tester** [comment]
New Gerrit review created for change 8a5888b147022b4586d30dcd7159e4fa6a31ec0e: https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5339

**Comment by sqla-tester** [comment]
**Michael Bayer** (zzzeek) wrote:

recheck

limited py313 builds to sqlite only

View this in Gerrit at https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5339

**Comment by sqla-tester** [comment]
Gerrit review https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/5339 has been **merged**. Congratulations! :)

**Comment by CaselIT** [comment]
this can be closed, since it was merged
