### ISSUE TITLE
Query.from_statement fails with due to column_property

### ISSUE THREAD

**Issue by torsdag** [sqlalchemy/sqlalchemy#10114]
### Describe the bug

We are seeing issues when using column properties together with `Query.from_statement` as it appears that it fails to resolve the name / label for the property  . 

It looks like a similar issue was addressed for sqlalchemy 2 ( https://github.com/sqlalchemy/sqlalchemy/issues/9273) any chance of this making it into 1.4? 

cheers

>

### SQLAlchemy Version in Use

1.4.49

### DBAPI (i.e. the database driver)

pysqlite

### Database Vendor and Major Version

SQLite, Mariadb

### Python Version

3.11

### Operating system

Linux

### To Reproduce

```python
import sqlalchemy
import sqlalchemy.orm

Base = sqlalchemy.orm.declarative_base()


class Entity(Base):
    __tablename__ = 'entity'

    id = sqlalchemy.Column(
        sqlalchemy.Integer, primary_key=True
    )

    c_property = sqlalchemy.orm.column_property(
        sqlalchemy.select(
            1
        ).as_scalar()
    )


engine = sqlalchemy.create_engine(
    'sqlite:///:memory:', echo=True
)

Base.metadata.create_all(engine)

Session = sqlalchemy.orm.sessionmaker(
    bind=engine
)


Session().query(Entity).from_statement(sqlalchemy.select(Entity.id)).all()
```

### Error
```
Traceback (most recent call last):
  File "../test.py", line 32, in <module>
    Session().query(Entity).from_statement(sqlalchemy.select(Entity.id)).all()
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/orm/query.py", line 2773, in all
    return self._iter().all()
           ^^^^^^^^^^^^
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/orm/query.py", line 2916, in _iter
    result = self.session.execute(
             ^^^^^^^^^^^^^^^^^^^^^
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/orm/session.py", line 1720, in execute
    result = compile_state_cls.orm_setup_cursor_result(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/orm/context.py", line 349, in orm_setup_cursor_result
    return loading.instances(result, querycontext)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/orm/loading.py", line 88, in instances
    with util.safe_reraise():
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/orm/loading.py", line 69, in instances
    *[
     ^
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/orm/loading.py", line 70, in <listcomp>
    query_entity.row_processor(context, cursor)
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/orm/context.py", line 2631, in row_processor
    _instance = loading._instance_processor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/orm/loading.py", line 796, in _instance_processor
    prop.create_row_processor(
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/orm/interfaces.py", line 658, in create_row_processor
    strat.create_row_processor(
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/orm/strategies.py", line 255, in create_row_processor
    col = adapter.columns[col]
          ~~~~~~~~~~~~~~~^^^^^
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/util/_collections.py", line 762, in __missing__
    self[key] = val = self.creator(self.weakself(), key)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/sql/util.py", line 1036, in _locate_col
    c = ClauseAdapter.traverse(self, col)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 619, in traverse
    return replacement_traverse(obj, self.__traverse_options__, replace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 848, in replacement_traverse
    obj = clone(
          ^^^^^^
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 844, in clone
    newelem._copy_internals(clone=clone, **kw)
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/sql/elements.py", line 4634, in _copy_internals
    self._element = clone(self._element, **kw)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 827, in clone
    newelem = replace(elem)
              ^^^^^^^^^^^^^
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/sql/visitors.py", line 615, in replace
    e = v.replace(elem)
        ^^^^^^^^^^^^^^^
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/sql/util.py", line 914, in replace
    return self._corresponding_column(col, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/sql/util.py", line 852, in _corresponding_column
    newcol = self.selectable.exported_columns.get(col.name)
                                                  ^^^^^^^^
  File "../.venv/lib64/python3.11/site-packages/sqlalchemy/sql/elements.py", line 4066, in __getattr__
    return getattr(self.element, attr)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Select' object has no attribute 'name'``` 
```
### Additional context

This appears to work in sqlalchemy 2.0.19.

**Comment by zzzeek** [comment]
this was fixed as part of #6245 in 2acc9ec1281b2818bd4480 which was a full refactor of from_statement(), delivered in the first beta of 2.0, so a backport is not an option, nor do we generally backport fixes to the "maintenance" version (1.4 in this case) that are not regressions or things that would affect currently running code (like a connection pool race condition).

the column_property here can be omitted using `defer()` or `with_only_columns()`:

```py
Session().query(Entity).options(sqlalchemy.orm.load_only(Entity.id)).from_statement(sqlalchemy.select(Entity.id)).all()

Session().query(Entity).options(sqlalchemy.orm.defer(Entity.c_property)).from_statement(sqlalchemy.select(Entity.id)).all()

```
