### ISSUE TITLE
Accessing backref attributes on the type level does not work

### ISSUE THREAD

**Issue by lukasjuhrich** [sqlalchemy/sqlalchemy#6616]
**Describe the bug**
I'm not sure whether that's “formally” supported, but I encountered the following behavioral change:

Accessing a relationship defined implicitly via `backref` on the type level does not work in sqlalchemy v1.4.16 or 1.4.17.
This inhibits using these relationships e.g. in a `.join` statement in a query.

I couldn't find something obviously related in the 1.16 release notes.

**To Reproduce**
```py
from sqlalchemy import *
from sqlalchemy.orm import *

Base = declarative_base()

class User(Base):
    __tablename__ = 'user'
    id = Column(Integer, primary_key=True)
    name = Column(String)

    addresses = relationship("Address", backref="user")

class Address(Base):
    __tablename__ = 'address'
    id = Column(Integer, primary_key=True)
    email = Column(String)
    user_id = Column(Integer, ForeignKey('user.id'))

Address.user
```
The last line works in 1.4.15, but throws the following error in 1.4.{16,17}:

**Error**
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-4c98dc408eac> in <module>
----> 1 Address.user

AttributeError: type object 'Address' has no attribute 'user'
```

**Versions.**
 - OS: Linux 5.12.4
 - Python: 3.9.1
 - SQLAlchemy: 1.4.{16,17}

**Comment by zzzeek** [comment]
this is expected, and fails for me in all versions and it's because the mappers are not configured.  solution:

```python
    configure_mappers()
    Address.user
```

this is part of the reason why "backref" is de-emphasized in the current documentation for using [back_populates](https://docs.sqlalchemy.org/en/14/tutorial/orm_related_objects.html#working-with-related-objects):

```python
class User(Base):
    __tablename__ = 'user'
    id = Column(Integer, primary_key=True)
    name = Column(String)

    addresses = relationship("Address", back_populates="user")

class Address(Base):
    __tablename__ = 'address'
    id = Column(Integer, primary_key=True)
    email = Column(String)
    user_id = Column(Integer, ForeignKey('user.id'))

    user = relationship("User", back_populates="addresses")
```

**Comment by zzzeek** [comment]
as to why it works for you in 1.4.15 i would assume your real world example has somethign else going on that happens to trigger configure_mappers() ahead of time for some reason.  would be good to know what that is.

**Comment by lukasjuhrich** [comment]
Thanks for the quick reply. We actually favor `back_populates` for new code, but did not change that retrospectively.

For context, side-by-side to our declarative model we define e.g. views with sqlalchemy queries depending on the declarative classes (for an example see [this usage](https://github.com/agdsn/pycroft/blob/develop/pycroft/model/hades.py#L65)) – but these are defined at _import time_ and hence need the mapper to be configured. Judging by [the docs on configure_mappers](https://docs.sqlalchemy.org/en/14/orm/mapping_api.html#sqlalchemy.orm.configure_mappers), I'm not quite sure how this should've worked in 1.4.15. I know nothing about the mapper internals though.

I will crank up the log level and see whether prepending `configure_mappers` will work.
