### ISSUE TITLE
Join-Dependent Relationship Hybrid Bug v1.4

### ISSUE THREAD

**Issue by exrich** [sqlalchemy/sqlalchemy#6386]
Join dependent relationship hybrid don't work the same way in 1.4 as they do in 1.3.  Take the example in the docs:

```py
from sqlalchemy import Column, Integer, ForeignKey, Numeric, String
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.hybrid import hybrid_property

Base = declarative_base()

class SavingsAccount(Base):
    __tablename__ = 'account'
    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey('user.id'), nullable=False)
    balance = Column(Numeric(15, 5))

class User(Base):
    __tablename__ = 'user'
    id = Column(Integer, primary_key=True)
    name = Column(String(100), nullable=False)

    accounts = relationship("SavingsAccount", backref="owner")

    @hybrid_property
    def balance(self):
        if self.accounts:
            return self.accounts[0].balance
        else:
            return None

    @balance.expression
    def balance(cls):
        return SavingsAccount.balance

>>> print(Session().query(User, User.balance).
...       join(User.accounts).filter(User.balance > 5000))
```

Works fine. However  if I change the name of the expression to test

```py
from sqlalchemy import Column, Integer, ForeignKey, Numeric, String
from sqlalchemy.orm import relationship
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.ext.hybrid import hybrid_property

Base = declarative_base()

class SavingsAccount(Base):
    __tablename__ = 'account'
    id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey('user.id'), nullable=False)
    balance = Column(Numeric(15, 5))

class User(Base):
    __tablename__ = 'user'
    id = Column(Integer, primary_key=True)
    name = Column(String(100), nullable=False)

    accounts = relationship("SavingsAccount", backref="owner")

    @hybrid_property
    def test(self):
        if self.accounts:
            return self.accounts[0].balance
        else:
            return None

    @test.expression
    def test(cls):
        return SavingsAccount.balance
    
print(Session().query(User, User.test).join(User.accounts).filter(User.test > 5000))
```

Then I get this error:

AttributeError: type object 'SavingsAccount' has no attribute 'test'

Couldn't find a mention of this in the changelog and it worked fine in 1.3.  Sqlalchemy version is 1.4.7

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**add optional proxy_class to track w/ proxy_key** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2784

**Comment by zzzeek** [comment]
thanks for reporting
