### ISSUE TITLE
cannot import name '_literal_as_text' from 'sqlalchemy.sql.expression' SQLAlchemy==1.4.6

### ISSUE THREAD

**Issue by anthony-sarkis** [sqlalchemy/sqlalchemy#6224]
**Describe the bug**
```
from sqlalchemy.sql.expression import _literal_as_text
ImportError: cannot import name '_literal_as_text' from 'sqlalchemy.sql.expression'
```
Example where another import `Executable` works fine:
![image](https://user-images.githubusercontent.com/18080164/113959836-63524c00-97d8-11eb-9756-00878b4906c7.png)

**Expected behavior**
Import without error
Appears like a regression 

**To Reproduce**
Try importing in console.

**Error**
ImportError

**Versions.**
 - OS: Windows 10
 - Python: Python 3.9.2
 - SQLAlchemy:  1.4.6
 - Database:  N/A
 - DBAPI:  N/A

**Additional context**
When upgraded from 1.3.18 - worked fine in that version

**Have a nice day!**
You too! :)

**Comment by zzzeek** [comment]
hey there -

_literal_as_text has been removed.    as an underscored method, it's not part of public API, so no regression here.

**Comment by anthony-sarkis** [comment]
Hey Mike,
Thanks - that makes sense. And thanks for fast response.

This was the use case (originally from https://github.com/sqlalchemy/sqlalchemy/wiki/Explain I think)
```
class explain_postgres(Executable, ClauseElement):
    def __init__(self, stmt, analyze=True):
        self.statement = _literal_as_text(stmt)
        ...

@compiles(explain_postgres, 'postgresql')
def pg_explain(element, compiler, **kw):
    text = "EXPLAIN "
    text += compiler.process(element.statement, **kw)
```
I see the function was 
https://github.com/sqlalchemy/sqlalchemy/compare/rel_1_3_18...master#diff-04c0f9496fbc845d94abca3f670597a55da015d8ce56154a3408a73267ddedbfL4464
```
def _literal_as_text(element, allow_coercion_to_text=False):
    if allow_coercion_to_text:
        return _literal_as(element, TextClause)
    else:
        return _literal_as(element, _no_text_coercion)
```

Sorry to be a bother, may I trouble you to please suggest an alterative direction if possible?

**Comment by zzzeek** [comment]
it has an update for 1.4 :   https://github.com/sqlalchemy/sqlalchemy/wiki/Query-Plan-SQL-construct

**Comment by anthony-sarkis** [comment]
Oh perfect!! Thank you very much :)
