### ISSUE TITLE
dialect.has_table calls no-existent exec_driver_sql (SQLite)

### ISSUE THREAD

**Issue by gilesbrown** [sqlalchemy/sqlalchemy#5780]
**Describe the bug**
This code
```python
import sqlalchemy

print(sqlalchemy.__version__)
engine = sqlalchemy.create_engine('sqlite://')
# this works on 1.3.20
engine.dialect.has_table(engine, 'mytable')
```
Raises the following exception:
```
% python bug.py
1.4.0b1
Traceback (most recent call last):
  File "bug.py", line 6, in <module>
    engine.dialect.has_table(engine, 'mytable')
  File "/Users/gbrown/.virtualenvs/foo/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/base.py", line 1650, in has_table
    info = self._get_table_pragma(
  File "/Users/gbrown/.virtualenvs/foo/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/base.py", line 2172, in _get_table_pragma
    cursor = connection.exec_driver_sql(statement)
AttributeError: 'Engine' object has no attribute 'exec_driver_sql'
```

**Expected behavior**
I expected it to return `False` with no traceback as it used to under 1.3.20.

**To Reproduce**
See bug description above.

**Versions.**
 - OS: macOS Catalina
 - Python: 3.8.6
 - SQLAlchemy: 1.4.0b1
 - Database: SQLite
 - DBAPI:

**Additional context**
Maybe I should have been using `engine.has_table('mytable')` and I see that is being deprecated.  I know how to fix my code to avoid this.  I just registering as an FYI.  Thanks.

**Have a nice day!**
You too.  Cheers.

**Comment by zzzeek** [comment]
hey there -

``engine.dialect.has_table()`` is not public API to be used on the outside and only accepts a Connection object.   in 1.3, the "has_table()" approach is currently  [engine.has_table()](https://docs.sqlalchemy.org/en/13/core/connections.html?highlight=has_table#sqlalchemy.engine.Engine.has_table), which ideally should be present on the inspector but unfortunately in 1.3 it appears it is not.

in 1.4 has_table() is available on [the inspector](https://docs.sqlalchemy.org/en/14/core/reflection.html?highlight=has_table#sqlalchemy.engine.reflection.Inspector.has_table) which is where it will be long term.

**Comment by gilesbrown** [comment]
Sure, but it is my impression that the non-public nature of `engine.dialect.has_table` isn't so clear? (no underscore?) 🤷‍♂️ 

https://github.com/search?l=Python&q=engine.dialect.has_table&type=Code

Anyway as long as you're comfortable with it, thats fine by me.  I'm just flagging it in case it was unintended.

Thanks for SQLAlchemy.  It's awesome!

**Comment by zzzeek** [comment]
> Sure, but it is my impression that the non-public nature of `engine.dialect.has_table` isn't so clear? (no underscore?) man_shrugging

it's a public method for dialect authors in that it is part of a publicly extensible class called [Dialect](https://docs.sqlalchemy.org/en/13/core/internals.html?highlight=has_table#sqlalchemy.engine.interfaces.Dialect) and also is [documented](https://docs.sqlalchemy.org/en/13/core/internals.html?highlight=has_table#sqlalchemy.engine.default.DefaultDialect.has_table) as receiving a Connection object, not an Engine.      The actual classification for these methods would be best described as "protected" in the Java sense, that is, accessible to subclasses as well as the enclosing package.

Engine [will no longer have an execute method](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#implicit-and-connectionless-execution-bound-metadata-removed) in 2.0 so along with many other similar changes there should be far fewer confusing ambiguities like this.   


> 
> Thanks for SQLAlchemy. It's awesome!

thanks!

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Explicitly test for Connection in dialect.has_table()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2741

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **master** branch:

**Explicitly test for Connection in dialect.has_table()** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/2741
