### ISSUE TITLE
accommodate driver-specific range objects as parameters

### ISSUE THREAD

**Issue by lelit** [sqlalchemy/sqlalchemy#8690]
### Describe the bug

Trying out SA 2.0.0b1 with an application on mine, already working with 1.4.42 without issues nor warnings generated by `SQLALCHEMY_WARN_20=1`, I got an unexpected `'DateRange' object has no attribute 'bounds'` exception.

### To Reproduce

```python
from sqlalchemy import create_engine, Table, Column, Integer, String, MetaData, text, select
from sqlalchemy.dialects.postgresql import DATERANGE


metadata_obj = MetaData()

users = Table(
    "users",
    metadata_obj,
    Column("id", Integer, primary_key=True),
    Column("name", String(30)),
    Column("fullname", String),
    Column("validity", DATERANGE)
)

engine = create_engine("postgresql://foo:bar@localhost/testrange", echo=True)
metadata_obj.create_all(engine)

c = engine.connect()
q1 = text("SELECT daterange(CURRENT_DATE, (CURRENT_DATE + INTERVAL '1 year')::date, '[)')")
v = c.scalar(q1)
print(v)

q2 = select(users.c.id).where(users.c.validity == v)
print(c.scalar(q2))
```

### Error

```
2022-10-20 19:17:04,474 INFO sqlalchemy.engine.Engine select pg_catalog.version()
2022-10-20 19:17:04,474 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-10-20 19:17:04,475 INFO sqlalchemy.engine.Engine select current_schema()
2022-10-20 19:17:04,475 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-10-20 19:17:04,475 INFO sqlalchemy.engine.Engine show standard_conforming_strings
2022-10-20 19:17:04,475 INFO sqlalchemy.engine.Engine [raw sql] {}
2022-10-20 19:17:04,476 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-10-20 19:17:04,481 INFO sqlalchemy.engine.Engine SELECT pg_catalog.pg_class.relname 
FROM pg_catalog.pg_class JOIN pg_catalog.pg_namespace ON pg_catalog.pg_namespace.oid = pg_catalog.pg_class.relnamespace 
WHERE pg_catalog.pg_class.relname = %(table_name)s AND pg_catalog.pg_class.relkind = ANY (ARRAY[%(param_1)s, %(param_2)s, %(param_3)s, %(param_4)s, %(param_5)s]) AND pg_catalog.pg_table_is_visible(pg_catalog.pg_class.oid) AND pg_catalog.pg_namespace.nspname != %(nspname_1)s
2022-10-20 19:17:04,481 INFO sqlalchemy.engine.Engine [generated in 0.00054s] {'table_name': 'users', 'param_1': 'r', 'param_2': 'p', 'param_3': 'f', 'param_4': 'v', 'param_5': 'm', 'nspname_1': 'pg_catalog'}
2022-10-20 19:17:04,483 INFO sqlalchemy.engine.Engine COMMIT
2022-10-20 19:17:04,483 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2022-10-20 19:17:04,484 INFO sqlalchemy.engine.Engine SELECT daterange(CURRENT_DATE, (CURRENT_DATE + INTERVAL '1 year')::date, '[)')
2022-10-20 19:17:04,484 INFO sqlalchemy.engine.Engine [generated in 0.00038s] {}
[2022-10-20, 2023-10-20)
Traceback (most recent call last):
  File "/nix/store/94dyaydmfj9km4bi1gzhi1kx1lb5614l-python3-3.10.5-env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1786, in _execute_context
    context = constructor(
  File "/nix/store/94dyaydmfj9km4bi1gzhi1kx1lb5614l-python3-3.10.5-env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1290, in _init_compiled
    d_param = {
  File "/nix/store/94dyaydmfj9km4bi1gzhi1kx1lb5614l-python3-3.10.5-env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1291, in <dictcomp>
    key: flattened_processors[key](compiled_params[key])
  File "/nix/store/94dyaydmfj9km4bi1gzhi1kx1lb5614l-python3-3.10.5-env/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 516, in to_range
    value.lower, value.upper, value.bounds, value.empty
AttributeError: 'DateRange' object has no attribute 'bounds'. Did you mean: '_bounds'?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/pp.py", line 25, in <module>
    print(c.scalar(q2))
  File "/nix/store/94dyaydmfj9km4bi1gzhi1kx1lb5614l-python3-3.10.5-env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1277, in scalar
    return meth(
  File "/nix/store/94dyaydmfj9km4bi1gzhi1kx1lb5614l-python3-3.10.5-env/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 505, in _execute_on_scalar
    return self._execute_on_connection(
  File "/nix/store/94dyaydmfj9km4bi1gzhi1kx1lb5614l-python3-3.10.5-env/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 487, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/nix/store/94dyaydmfj9km4bi1gzhi1kx1lb5614l-python3-3.10.5-env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1616, in _execute_clauseelement
    ret = self._execute_context(
  File "/nix/store/94dyaydmfj9km4bi1gzhi1kx1lb5614l-python3-3.10.5-env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1792, in _execute_context
    self._handle_dbapi_exception(
  File "/nix/store/94dyaydmfj9km4bi1gzhi1kx1lb5614l-python3-3.10.5-env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2303, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/nix/store/94dyaydmfj9km4bi1gzhi1kx1lb5614l-python3-3.10.5-env/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1786, in _execute_context
    context = constructor(
  File "/nix/store/94dyaydmfj9km4bi1gzhi1kx1lb5614l-python3-3.10.5-env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1290, in _init_compiled
    d_param = {
  File "/nix/store/94dyaydmfj9km4bi1gzhi1kx1lb5614l-python3-3.10.5-env/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1291, in <dictcomp>
    key: flattened_processors[key](compiled_params[key])
  File "/nix/store/94dyaydmfj9km4bi1gzhi1kx1lb5614l-python3-3.10.5-env/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 516, in to_range
    value.lower, value.upper, value.bounds, value.empty
sqlalchemy.exc.StatementError: (builtins.AttributeError) 'DateRange' object has no attribute 'bounds'
[SQL: SELECT users.id 
FROM users 
WHERE users.validity = %(validity_1)s::DATERANGE]

``` 

### Versions

- OS: NixOS
- Python: 3.10.5
- SQLAlchemy: 2.0.0b1
- Database: PostgreSQL
- DBAPI: psycopg2

### Additional context

Effectively, in [psycopg2.py#L516](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/dialects/postgresql/psycopg2.py#L516) there is this code:
```
        def to_range(value):
            if not isinstance(value, (str, NoneType)):
                value = Range(
                    value.lower, value.upper, value.bounds, value.empty
                )
            return value
```

The value is a `DateRange` instance, coming from `psycopg2` that does not seem to expose a `bounds` property as it does for example for `lower`: https://github.com/psycopg/psycopg2/blob/master/lib/_range.py#L45

**Comment by zzzeek** [comment]
so we changed our DateRange to be native, so when you use that text() statement, it has no way to convert the value to our own DateRange.   so for now, to get the expected type back, do this:

```py
q1 = text(
    "SELECT daterange(CURRENT_DATE, (CURRENT_DATE + INTERVAL '1 year')::date, '[)')"
).columns(column("x", DATERANGE))
```

then it works.

However, we should be able to accommodate the native driver versions of these when given as parameters, just to make things easier.

**Comment by lelit** [comment]
Thank you Mike. 

The solution you suggest is not easy: those two queries are actually dinamically generated by my own [data loader](https://pypi.org/project/metapensiero.sqlalchemy.dbloady/). I will think about a different workaround, or wait for the next beta, whichever comes first :rofl:

**Comment by sqla-tester** [comment]
**Mike Bayer** has proposed a fix for this issue in the **main** branch:

**Only convert Range for sqlalchemy Range object** https://gerrit.sqlalchemy.org/c/sqlalchemy/sqlalchemy/+/4142

**Comment by zzzeek** [comment]
that change I made is how this should have been done in the first place, I was already allowing string-based ranges to be passed directly as that was another use case people had.

**Comment by lelit** [comment]
Super! :1st_place_medal:
