### ISSUE TITLE
Installation of versions > 1.3.13 fails via pipenv in python 3.7.4

### ISSUE THREAD

**Issue by mccolin** [sqlalchemy/sqlalchemy#5199]
Installing versions > 1.3.13 is failing for us, it appears due to an integrated `enum` dependency.

When using 1.3.13 this was not an issue. Builds with 1.3.14 and 1.3.15 fail in this way.

Error: 
```AttributeError: module 'enum' has no attribute 'IntFlag'```

Stack:
* Python 3.7.4
* pipenv for dependency management
* `sqlalchemy = "*"` dependency line

Output during `pipenv install`:

```
An error occurred while installing sqlalchemy==1.3.14 --hash=sha256:b92d2de62e43499d85b1780274d1b562e5159c7996f6f04a9bb46cf681ced45f! Will try again.
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1874, in do_install
[pipenv.exceptions.InstallError]:       keep_outdated=keep_outdated
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Collecting sqlalchemy==1.3.14', '  Using cached SQLAlchemy-1.3.14.tar.gz (6.1 MB)', '  Installing build dependencies: started', "  Installing build dependencies: finished with status 'error'"]
[pipenv.exceptions.InstallError]: ['ERROR: Command errored out with exit status 1:', "   command: /root/.local/share/virtualenvs/ks-nQj0AsbL/bin/python /root/.local/share/virtualenvs/ks-nQj0AsbL/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-daar_xok/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel", '       cwd: None', '  Complete output (14 lines):', '  Traceback (most recent call last):', '    File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main', '      "__main__", mod_spec)', '    File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code', '      exec(code, run_globals)', '    File "/root/.local/share/virtualenvs/ks-nQj0AsbL/lib/python3.7/site-packages/pip/__main__.py", line 16, in <module>', '      from pip._internal.cli.main import main as _main  # isort:skip # noqa', '    File "/root/.local/share/virtualenvs/ks-nQj0AsbL/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 5, in <module>', '      import locale', '    File "/usr/local/lib/python3.7/locale.py", line 16, in <module>', '      import re', '    File "/usr/local/lib/python3.7/re.py", line 143, in <module>', '      class RegexFlag(enum.IntFlag):', "  AttributeError: module 'enum' has no attribute 'IntFlag'", '  ----------------------------------------', "ERROR: Command errored out with exit status 1: /root/.local/share/virtualenvs/ks-nQj0AsbL/bin/python /root/.local/share/virtualenvs/ks-nQj0AsbL/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-daar_xok/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output."]
```

**Comment by CaselIT** [comment]
duplicate of https://github.com/sqlalchemy/sqlalchemy/issues/5195

To solve this you can uninstall enum34, that is not compatible with python 3.7+

**Comment by CaselIT** [comment]
Please reopen if the issue is not solved by uninstalling enum34

**Comment by CaselIT** [comment]
I've opened an issue in enum34 https://bitbucket.org/stoneleaf/enum34/issues/31/make-the-install-a-noop-on-python36

**Comment by zzzeek** [comment]
why would people not have this issue installing 1.3.13 or literally any python package?  this has nothing to do with SQLAlchemy, the stack traces are entirely from pip

**Comment by zzzeek** [comment]
if you google "AttributeError: module 'enum' has no attribute 'IntFlag'"" this issue is everywhere for years.   very strange it gets reported with us twice in a row like that...

**Comment by mccolin** [comment]
I appreciate this response, but our project does not include enum34 and this issue did not crop up until the SQLAlchemy releases of 1.3.14 and 1.3.15.

Has no one else seen this issue happen at install time with the version increase?

The stack traces are included as they include install failures happening during the installation of SQLAlchemy.

**Comment by zzzeek** [comment]
SQLAlchemy does not include enum34 either.  the stack trace you posted is from pip.   you should be getting this error for any package which you install with pip in the same way; note pip caches local files so to reproduce with say, SQLAlchemy 1.3.8, use "pip install SQLAlchemy==1.3.8 --no-cache-dir", should do the same thing

**Comment by CaselIT** [comment]
> I appreciate this response, but our project does not include enum34 and this issue did not crop up until the SQLAlchemy releases of 1.3.14 and 1.3.15.

Another package may depend on it, so it may have been installed by it. Does `pip list` list it?

If it's not listed and you still have the problem it may be something else causing it.

**Comment by mcauto** [comment]
> I appreciate this response, but our project does not include enum34 and this issue did not crop up until the SQLAlchemy releases of 1.3.14 and 1.3.15.
> 
> Has no one else seen this issue happen at install time with the version increase?
> 
> The stack traces are included as they include install failures happening during the installation of SQLAlchemy.

@mccolin Did you remove global enum34?

I had the same issue with ujson.

https://github.com/ultrajson/ultrajson/issues/376
